### ISSUE TITLE
Force piggybacking.

### ISSUE THREAD

**Issue by ezequiel-umu** [mcollina/node-coap#100]
I can't see a way to force piggybacked responses, which is desirable for working with motes (by reducing the amount of packets and thus the probability of loss).

Is it possible?

**Comment by mcollina** [comment]
It is not currently possible. Piggypack will happen if you reply within 50ms: https://github.com/mcollina/node-coap/blob/master/lib/outgoing_message.js#L46.

It would be great to have this configurable at server level. Would you like to send a PR?

**Comment by neophob** [comment]
I've added the piggyback timeout as config value on my branch, see

https://github.com/neophob/node-coap/commit/6979b5a8a3dccf7d60eb4be869e53ecf361629e2
https://github.com/neophob/node-coap/commit/cf33119d0a4b752f18a2a50159dcd4f0b3e0c6dc

maybe this helps? Should I create a PR?

**Comment by mcollina** [comment]
@neophob please do :)
