### ISSUE TITLE
Tests fail with Node.js v5

### ISSUE THREAD

**Issue by dmoranj** [mcollina/node-coap#105]
It seems the library does not integrate well with Node.js v5. It works well with versions from 0.10 to 4.3, but something changed from version 4 to version 5 that makes most of the tests fail. Travis checks with version 5 are temporarily disable to allow contributing while we fix this.

**Comment by psorowka** [comment]
@dmoranj I just also stumbled over that. I am not enough into the coap lib to have an instant clue. But what I can tell is that the breaking change does not seem to be between 4 and 5 but rather 5.6 to 5.7. I just ran the test on 5.5 and 5.6 and both were fine. only 5.7 fails in my case.

**Comment by mcollina** [comment]
It will likely be fixed in 5.7.1. I've done a good refactoring of dgram,
and there was a regression.
Il giorno sab 27 feb 2016 alle 02:43 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by neophob** [comment]
I assume this can be closed?

**Comment by mcollina** [comment]
Yes
