### ISSUE TITLE
doesn't browserify

### ISSUE THREAD

**Issue by janeksz** [mcollina/node-coap#106]
Hi Mateo,

I’m using your npm coap module, thanks for sharing.
It works on webserver.

Now I wanted to use it on client side.
After installing browserify http://browserify.org/#install and following their example:
1)	From directory …\webserver\simpleWebserver_25_02_2016\node_modules\coap
I invoked: browserify index.js –o ccoap.js
And created the file ccoap.js
2)	On client side I have the code:
<script type="text/javascript" src="/ccoap.js"></script>
var client_coap = require('coap');

  $('#test1').click(function(){
  alert("testing CoAP");
});

That give an error: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create ccoap.js:230:2

Indicated by web console in Firefox 38.0

If I remove var client_coap = require('coap'); I have the alert, without it no.
Can you help to resolve it?

Regards

Jan

**Comment by mcollina** [comment]
It doesn't work in the browser :/. Coap is a UDP-based protocol, and currently there is no UDP API (or `dgram` implementation) in the Browser.
