### ISSUE TITLE
the .on("error", function(){}) event doesn't fire

### ISSUE THREAD

**Issue by Iman-mohamed** [mcollina/node-coap#107]
Hi,
I'm using the library as a CoAP client when there's no errors it works fine but when I switch off the CoAP server .. the .on("error", function(){}) event didn't fire... I'm including my client code :
`var coap = require( 'coap' );
  req = coap.request( "coap://localhost/home" );

  req.on( "response", function( res ) {
    res.pipe( process.stdout );
    console.log ("res code: " + res.code );
    console.log( "res: " + JSON.stringify( res ) );
    console.log("req obj: " + require("util").inspect(req) );
  });
  req.on( "error", function( e ) {
   console.log("Request error :" + e.toString() );
  });
  req.on( "finish", function() {
    console.log( "The CoAP request is finished" );
  });
  req.end();`

**Comment by mcollina** [comment]
The `'error'` event will fire after it has done all the retries and the requests times out. How long have you left this running?

**Comment by Iman-mohamed** [comment]
yes, I've go the error message "Error: No reply in 247s" after waiting 3 mints.
