### ISSUE TITLE
DTLS

### ISSUE THREAD

**Issue by heri16** [mcollina/node-coap#11]
If DTLS is not yet available, would libsodium via node-ffi work?

**Comment by dmoranj** [comment]
Have you tried the solution proposed in https://github.com/joyent/node/pull/6704 ? Maybe trying to push a proposed solution will be easier than creating a binding from scratch.

**Comment by mcollina** [comment]
That would be a very long-term solution, likely 1+ year to get it into a
stable release of node. I saw that, but I have very little time to dedicate
to it. I would be grateful if you contribute there, or make a npm module
for dtls.
Il giorno ven 13 feb 2015 alle 01:51 Daniel Moran <notifications@github.com>
ha scritto:

**Comment by dmoranj** [comment]
Concerning this subject,  an idea came to my mind that may be a simple and efficient solution for the problem (or a disposable crazy idea, who knows): Would it be possible to use a DTLS terminator the same way a SSL terminator is used? This way we could decouple the DTLS securization from the library, and have a CPU efficient module deal with all the cryptographic stuff. We have used NGINX for SSL termination in the past but I don't know if it provides similar features for DTLS or whether building a module to support that would be feasible or a complete hell. Have you tried this approach? Do you think it could be possible to solve the problem this way?

**Comment by dmoranj** [comment]
I mistakenly closed the issue, sorry.

**Comment by mcollina** [comment]
DTLS support is also needed for clients, not only for servers.

Basically, we need to write a native module to support DTLS in node. It is likely 2-4 weeks of work, given a quick estimate.

**Comment by Rantanen** [comment]
I started a Node.js DTLS module for WebRTC purposes at: [Rantanen/node-dtls](http://github.com/Rantanen/node-dtls)

The module is a bit unstable for now but it does implement DTLS 1.2 compatible handshake and data transmission so I feel like the worst parts are done. Unfortunately the only two DTLS endpoints I've had to test it against have been the openssl s_client/s_server commands and the module itself.

I've not gone through the CoAP references (just saw it mentioned in one of the Node.js PRs) so I'm not sure if CoAP would need support for certain (D)TLS extensions, etc. or what else would be needed to provide DTLS support for CoAP.

While I don't really have need for DTLS in CoAP (or even CoAP itself) I'm interested in more ways to test the DTLS module against different DTLS implementations. I'm currently playing catch up with the unit tests for the handshake handling and general test coverage, but once I'm satisfied with that I'll see if I can implement more of the DTLS basics such as handshake renegotiation, DTLS 1.0 support, Node 0.10 compatibility and then the various extensions such as heartbeat and quick session resume.

**Comment by mcollina** [comment]
Wooow, DTLS in pure JS, this is awesome! I would love to have support for this in this library! I am kind of low on bandwidth at the moment, but I look forward to this!

**Comment by Sean-Wang** [comment]
Please add DTLS features to node-coap, thx.

**Comment by mcollina** [comment]
@Sean-Wang DTLS apis are not exposed in node.js. Probably it will happen after the reconciliation release.

As a time frame, we will probably have this feature done before the end of the year.

**Comment by Sean-Wang** [comment]
Thanks @mcollina .

**Comment by msolters** [comment]
Hi, what is the current status of CoAP DTLS at this time?

**Comment by GiedriusM** [comment]
Currently DTLS is not implemented

**Comment by Hypfer** [comment]
However there seems to be this fork https://github.com/neustar/node-coap-dtls with working dtls for the client.

**Comment by rajshah4488** [comment]
Hello sir
Here you worked with temperature sensor. But, I am using Pi Camera so may I know how this code can be implemented. If you have any other reference then please share..

Thank you ...

**Comment by Torbadol** [comment]
Hi, does this news make this project to enable DTLS ?
https://nodejs.org/en/blog/vulnerability/march-2018-security-releases/

**Comment by reklatsmasters** [comment]
https://github.com/nodertc/dtls

Here is my experimental DTLS implementation in pure js. Client side only right now. Modern ciphers, message reordering, defragmentation already exists.

**Comment by reklatsmasters** [comment]
I testes `coap` with `@nodertc/dtls@0.6.0`. They works fine together!

Coap server is `libcoap@4.2.0`. Start server `./coap-server -A 127.0.0.1 -p 8088 -k deadbeaf -v 7`. See example and required modifications:

https://github.com/reklatsmasters/node-coap/commit/14d178aeb27a00238509b3c2503bbd8ac8ddfd59

```js
const coap  = require('../') // or coap
const dtls = require('@nodertc/dtls');

const socket = dtls.connect({
  type: 'udp4',
  remotePort: 8089,
  remoteAddress: '127.0.0.1',
  maxHandshakeRetransmissions: 3,
  alpn: 'coap',
  pskIdentity: 'coap',
  pskSecret: 'deadbeaf',
  cipherSuites: [
    'TLS_PSK_WITH_AES_128_GCM_SHA256',
    'TLS_PSK_WITH_AES_256_GCM_SHA384'
  ]
})

const agent = new coap.Agent({ socket });
const req = coap.request({ agent })

req.on('response', function(res) {
  res.pipe(process.stdout)
  socket.close();
})

req.end()
```

**Comment by GiedriusM** [comment]
Actually since v0.23.0 coap server and client can be used on top of any custom layer (including DTLS) as long as it provides a socket compatible with dgram socket API (https://nodejs.org/api/dgram.html), i.e. `close`, `connect`, `error`, `listening` and `message` events together with `address()`, `close()`, `[dis]connect()`, and `send()` functions:

```javascript
const customClientSock = ....;
const customServerSock = ...;

const server = coap.createServer();
server.on('request', (req, res) => {
  console.log('Server got request');
  res.end('Response');
});
server.listen(customServerSock, () => {
  const req = coap.request({ agent: new coap.Agent({ socket: customClientSock }) });
  req.on('response', res => {
    console.log('Client got response');
  });
  req.end();
});
```

I've successfully used this approach together with a [minimal mbedtls nodejs wrapper](https://github.com/GiedriusM/node-mbedtls) to do automated testing for a wakaama+gnutls server.

It would be cool to test how node-coap performs on top of other layers. Anyone willing to write an SMS socket wrapper? :)

**Comment by GiedriusM** [comment]
> Do you intend to contribute an official DTLS server implementation? 🙏

@beriberikix, what do you mean by "official"?

**Comment by beriberikix** [comment]
I got my wires crossed 🤦‍♂ 

I was wondering if @reklatsmasters was considering developing a server.

**Comment by reklatsmasters** [comment]
DTLS server is much more complex thing. It has more stringent security requirements (select cipher, alerts). Yes, all low-level primitives are implemented (aead, master/premaster keys, etc.), but i dunno... Besides, DTLS server is not *required* for WebRTC.

**Comment by ankit2002** [comment]
Hey @reklatsmasters, 
I tried your your above mentioned solution with `libcoap@4.2.0` and `@nodertc/dtls@0.6.0` and it doesn't seems to be working as I constantly get `Error: alert code 40` and `Defragmentation.ondata` error. I havn't change anything on the example code and just followed your command. Could you please tell me what the `code 40` and `code 10` means so I can debug it furthur. Thanks.

**Comment by reklatsmasters** [comment]
@heri16 This is an alert messages UNEXPECTED_MESSAGE and HANDSHAKE_FAILURE. It means mismatch client and server configurations or a bug in dtls client. Could you please create an issue in nodertc/dtls repo and attach protocol dump using wireshark?

**Comment by ankit2002** [comment]
@reklatsmasters Nevermind, I am using tinydtls which only supports 'TLS_PSK_WITH_AES_128_CCM_8' and 'TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8' `ciphers`. And these are not supported by yours library.

**Comment by reklatsmasters** [comment]
These ciphers deprecated or not recommended for using by spec.

вт, 24 сент. 2019 г., 11:05 Ankit Mishra <notifications@github.com>:
