### ISSUE TITLE
unable to obsere resource | node-coap

### ISSUE THREAD

**Issue by kaleemullah360** [mcollina/node-coap#112]
Hi @mcollina 
as I am very beginner so I need your help.

I am trying to get coap message sent by sensor mote using your `node-coap` lib.
I am able to get message but not able to observe the resource.
I am passing params like this `({url: 'coap://[aaaa::c30c:0:0:2]:5683/test/push', observe: true})`
therefor not sure how to pass `url` and `observe: true`.

```
const coap  = require('../') // or coap
       , req   = coap.request({url: 'coap://[aaaa::c30c:0:0:2]:5683/test/push', observe: true})
   req.on('response', function(res) {
     res.pipe(process.stdout)
   })
   req.end()
```

here is my code. please help me what I'm doing wrong.

**Comment by mcollina** [comment]
```js
var URL = require('url')
var opts = URL.parse('coap://[aaaa::c30c:0:0:2]:5683/test/push')
opts.observe = true
// same as before..
```
