### ISSUE TITLE
problem handling errors

### ISSUE THREAD

**Issue by janeksz** [mcollina/node-coap#114]
Hi,
I need some help with handling errors. If the server doesn't respond within a 247 seconds I have
'Request error :Error: No reply in 247s
timeout :Error: No reply in 247s'
my code:
    // check for timeout error
    req4.on('timeout', function (err) {
    console.log("timeout :" + err.toString() );
    coapserver4.close(function(){
        // close and reopen
        console.log("coap4 (other) close and reopen");
        coapserver4 = coap4.createServer({ type: 'udp6' }); // used for other GET POST methods
      });  
    });

Q1: how to change the timeout value?
Q1: how to properly handle the timeout error? How to cancel the timeout error?  I am trying to close and reopen the server, but the error keeps coming all the time.

**Comment by msolters** [comment]
Well hello again!

I really wish I knew how to change the timeout!  It is really annoying!

However, you can fix the errors by simply catching them:

```js
      var req = coap.request( example_request_object );
      
      // Here's the magic! As long as you listen for errors
      // they won't crash your app.
      req.on('error', function( error ) {
        console.error( error );
      });
 
      req.end();
```

You don't have to even print the errors or do anything at all.  As long as this listener exists, it prevents the app from halting when the errors inevitably occur.

**Comment by neophob** [comment]
take a look at v0.15, where you can specify custom timeouts: https://github.com/mcollina/node-coap/commit/ece604498ff7b9cc489d516e2496900c8fb1996d

**Comment by janeksz** [comment]
Thanks, I see the example:

var coapTiming = {
  ackTimeout:0.25,
  ackRandomFactor: 1.0,
  maxRetransmit: 3,
  maxLatency: 2,
  piggybackReplyMs: 10
};
coap.updateTiming(coapTiming);

which parameter specifically defines timeout?

**Comment by neophob** [comment]
Take a look at the other parameter options like maxRTT, maxTransmitSpan, maxTransmitWait etc. you can just print them out like:
```  log.debug('CoAP max RTT in seconds:', coap.parameters.maxRTT);```
