### ISSUE TITLE
SSL / TLS

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mcollina/node-coap#115]
Is it possible to set a CoAP server with SSL or TLS for secure communication?

**Comment by kaleemullah360** [comment]
With my Understanding `CoAP` runs over `UDP` layer. so can't use `SSL` / `TLS` but we can use `DTLS` (Data Link Security). more over if we implement `CoAP` over `TCP` then goal can be achieved.

**Comment by AdamMiltonBarker** [comment]
Hi thanks for the repy. I saw some info on that isn't DTLS not available in Node JS though meaning you can't make secure calls with this or have I read wrong.

**Comment by mcollina** [comment]
CoAP runs over UDP, but there is some effort in porting it to TCP and TLS. DTLS (tls for udp), is not currently supported in core, even though there is a js-only thing that we might integrate. 

I am fine if anyone would like to implement https://tools.ietf.org/html/draft-tschofenig-core-coap-tcp-tls-04, or any follow up on that, I will be more than happy to give them the commit bit and the lead maintainer role on this project.

**Comment by AdamMiltonBarker** [comment]
Yes I saw that just wanted confirmation that it wasn't possible.

**Comment by mcollina** [comment]
Duplicate of https://github.com/mcollina/node-coap/issues/11

**Comment by AdamMiltonBarker** [comment]
5 year later I was looking for this solution and found my own post :D Has DTLS has not been yet ?

**Comment by AdamMiltonBarker** [comment]
No worries will check it out thanks for the reply.

**Comment by JKRhb** [comment]
> No worries will check it out thanks for the reply.

You're welcome :) There is another CoAP implementation which already has support for DTLS which you could try out in the meantime: https://github.com/AlCalzone/node-coap-client As its name suggests it only has client support, however.

**Comment by AdamMiltonBarker** [comment]
I found this also which is based on your project, it has a DTLS server also: https://github.com/neustar/node-coap-dtls

**Comment by JKRhb** [comment]
> I found this also which is based on your project, it has a DTLS server also: https://github.com/neustar/node-coap-dtls not sure if the server is fully functioning yet, it says in the README not but will check it out

Ah, very cool, though :) Maybe it is possible to introduce some of the code in this repo as well // CC @jspark311

**Comment by jspark311** [comment]
@JKRhb Oh, wow. I forgot this repo existed. I haven't worked for Neustar since 2018. I no longer have any control over that repo. :-(
