### ISSUE TITLE
How to read RTT

### ISSUE THREAD

**Issue by janeksz** [mcollina/node-coap#116]
In Copper Coap I can see the RTT displayed like this:
**[aaaa::212:4b00:798:5606]:5683 (RTT: 138ms)** after successful POST
How to implement it with node-coap?
Is there a ACK receive event?

**Comment by mcollina** [comment]
There is not, you can listen for a response.

**Comment by janeksz** [comment]
Can you be more specific?

**Comment by kaleemullah360** [comment]
I've computed RTT in Node-CoAP lib in Node Js. its simple and tested. you can use it.

```
	var mote_uri = req.query.uri;
	var start = new Date();
	var req = coap.request('coap://[' + mote_uri + ']:5683/sens/mote')
	req.on('response', function(c_res) {
		var RTT = new Date() - start;
		console.info("Execution time: %dms", RTT);
		c_payload = decoder.write(c_res.payload);
	})
	req.end()
```

it return RTT in milliseconds.

**Comment by janeksz** [comment]
@kaleemullah360 
Thanks, I will use it as it gives a good indication on network/connection quality.
