### ISSUE TITLE
SMS COAP

### ISSUE THREAD

**Issue by oceddi** [mcollina/node-coap#119]
How hard/easy would it be to interface this COAP library to an SMS bearer (think the Twilio API) instead of UDP?  Are the appropriate abstractions in place for a fairly easy integration?

**Comment by mcollina** [comment]
I do not think it would be an easy job, and it's not really on the scope of
this library. But let me know and propose any change you might see fit.
Il giorno ven 6 mag 2016 alle 07:33 Dean McKee <notifications@github.com>
ha scritto:

**Comment by neophob** [comment]
timedout and no pending tasks
