### ISSUE TITLE
Blockwise2 does not work with multiple simultaneous clients

### ISSUE THREAD

**Issue by jkivilin** [mcollina/node-coap#120]
I've run in following problem with node-coap.

Client A starts large blockwise2 transfer from CoAP server. While client A is still transferring, client B makes small request to server. Now, block2cache entry for client A is cleared because client B request, and next blockwise2 request (block2.num >= 1) from client A goes back to upper level. Upper level generates different payload for client A and transfer gets corrupted and fails. Client A then retries large blockwise2 transfer from start. Now while client A is still transferring, client C makes small request to server... and so on.

Checking Etag will not solve issue at client as CoAP server has tens of active clients and server needs to scale to have 1000 to 10000 clients, ~10-100 new requests per second. Our large blockwise2 transfer can take several seconds, and will practically always end up failing.

**Comment by neophob** [comment]
fixed
