### ISSUE TITLE
URIs are sent unnormalized

### ISSUE THREAD

**Issue by guimier** [mcollina/node-coap#127]
According to the CoAP RFC, the `Uri-Path` option is a “string”, which is supposed to be encoded in the Net-Unicode (UTF-8 + NFC) format. Node-coap currently send URIs unchanged, allowing users to pass unnormalized strings.

I think `Uri-Path` (and potentially other “string” options) fall in the “imported from sources outside the CoAP protocol” category mentioned in the RFC.

**Comment by neophob** [comment]
@guimier any pending work here or should I close?
