### ISSUE TITLE
using same socket in Server and Agent for NAT traversal

### ISSUE THREAD

**Issue by radiumfl** [mcollina/node-coap#128]
An application server (using node-coap) needs communicate to a node (using other coap lib) behind of a NAT (https://en.wikipedia.org/wiki/Network_address_translation). the application server and the node act both CoAP server and CoAP client roles because both them need initiate request.

It requires node-coap use same socket for client and server roles. As the server role, the application gets the translated IP address/port which will be used for following request as a client. In current implementation, Agent and Server maintenance their own _sock separately.  If I simply assign Server._sock to Agent._sock, it causes Agent cannot get any response anymore. Is there any method to handle this issue? Thanks in advance!
Radiumfl

**Comment by kaleemullah360** [comment]
@radiumfl , helping you based on my experience and knowledge.
you can use [Socket IO](https://www.npmjs.com/package/socket.io) and if you're using Express Js with Node Js then Socket IO implementation would be difficult. so use [Express IO](https://www.npmjs.com/package/express.io). create ports and sockets connection. even you can use it in views.

**Comment by radiumfl** [comment]
@kaleemullah360 , Thanks a lot! However, how to apply Socket IO into node-coap?

**Comment by kaleemullah360** [comment]
it is pretty easy. if you are using Express Js so as I am using in my project. do these.

1. in your project open www file located at `~/Project/bin/www`
2. paste these two methods in `www` file

```
 var io = require('socket.io')(server);
 io.on('connection', function(socket){
  console.log("User Connected");
  // Not a Good Way
  //socket.emit('wsn-data',{data: "10,100,100,100,100"});

  socket.on('disconnect', function () {
    console.log("User Disconnected");
  });
data = "this is my test string";
io.sockets.emit('wsn-data', {"data": data }); // emit data to view/browser when response is arrived
```

then in view to get that data call socket io

```
    script.
    script(src='js/socket.io.js')
    script.
      var socket = io();
      socket.on('wsn-data', function(payload){
      console.log(payload.data);
```

**Comment by radiumfl** [comment]
@kaleemullah360 Now I understand. Thanks!
