### ISSUE TITLE
Multicast multiple interface binding

### ISSUE THREAD

**Issue by dwarburt** [mcollina/node-coap#129]
When trying to use node-coap for some multicast traffic today on multiple interfaces, I found that it cannot bind to multiple interfaces for multicast. The nodejs `socket.addMembership` documentation was recently updated (https://github.com/nodejs/node/pull/7244/files) and I suppose it's now necessary to iterate the available interfaces and bind to each one explicitly, probably using `os.networkInterfaces()`.

**Comment by mcollina** [comment]
Unfortunately, I do not have time to address this issue. I'll be happy to merge any contribution in this area.

**Comment by dwarburt** [comment]
So, I've got a start on this but trying to figure out how to add tests for it now: https://github.com/dwarburt/node-coap/tree/multi-multi
