### ISSUE TITLE
Error: Bad socket type specified.

### ISSUE THREAD

**Issue by jafarmollaei** [mcollina/node-coap#134]
I run your sample code (server.js), But I have this error:
 
dgram.js:87
  throw new Error('Bad socket type specified. Valid types are: udp4, udp6');
 
 
what’s my mistake?

**Comment by kaleemullah360** [comment]
@jafarmollaei paste your code snippet.
with the given information I can say that your socket is none of type udp4 or udp6

**Comment by jafarmollaei** [comment]
Dear
I solved that problem, same you wrote.
When I do update the node, that error not apeared.

Regards
