### ISSUE TITLE
possible to call `OutgoingMessage.end()` more than once

### ISSUE THREAD

**Issue by gfarrell** [mcollina/node-coap#138]
I discovered a bug in my own application code which would cause something like the following:

```
res.code = "2.04";
res.end();
```

even after another code had been set and the response stream had been `end()`ed.

I had been relying on `OutgoingMessage.end()` throwing if it is called more than once (since, surely, the stream can only be ended once) but that doesn't happen. Therefore the behaviour I was seeing was that a response would be sent, and then a second response would be sent with the same CoAP MID.

I'm assuming that this is not the desired behaviour of `OutgoingMessage`, so it should probably throw if it has already finished and `end()` is called. I'm happy to put together a PR for that if it sounds reasonable.

**Comment by mcollina** [comment]
@gfarrell please do! :)

**Comment by gfarrell** [comment]
This no longer seems to be happening, and I get an error thrown (so perhaps I need to investigate further). I have an MVE below, which throws an error (and no extra packets are sent).

### error:

```
> node coap-138-mve.js
server listening on 9084
got a request
exiting...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
```

### MVE:

```javascript
"use strict";

const coap = require("coap");

const port = 9084;

const server = coap.createServer({ type: "udp6" });

server.on("request", (req, res) => {
    console.log("got a request");
    res.code = 204;
    res.end("Thanks :)");

    setTimeout(() => {
        res.code = 400;
        res.end("Sorry :(");
    }, 100);
});

server.listen(port);

console.log(`server listening on ${port}`);

process.on("exit", () => {
    console.log("exiting...");
    server.close();
});
```
