### ISSUE TITLE
 Error: getaddrinfo ENOTFOUND in coap request

### ISSUE THREAD

**Issue by jsapna** [mcollina/node-coap#141]
Hi,

I need to send coap request with host created using some resource ids for example my host is like "AAS0345678008.TEAM-AAS-XXX-INSTALL.ENG.XXXX.NET" so I am sending the coap request with this host, port defined as 5683 and the proxy server IP is defined in proxy uri option. so my coap request options are -
 let options = {
       host : 'AAS0345678008.TEAM-AAS-XXX-INSTALL.ENG.XXXX.NET', 
        port: '5683',
        method: 'GET',
        pathname: '/stats',
        query: 'mod=data',      
         proxyUri: 'coap://72.121.26.204:5683',
    };
    let req = coap.request(options);

But I am getting getaddrinfo error. Can someone tell me why I am getting this error ? What is wrong with the host ?

Error logs :
Error: getaddrinfo ENOTFOUND AAS0345678008.TEAM-AAS-XXX-INSTALL.ENG.XXXX.NET
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by jsapna** [comment]
I am using version v6.9.5. The same host is accessible from another coap client through command but it is not accessible in node coap. This is the problem.

**Comment by jsapna** [comment]
We are looking into the code how the proxyUri option is handled but we didn't find the place where code is sending coap request on proxy address when proxyUri is defined.  In fact the socket is sending the message always to the host address and port whether proxy is defined or not.

**Comment by GiedriusM** [comment]
For me the following code does resolve the address and send out CoAP request to 72.52.4.120 (although gets no response):

```javascript
const coap = require('coap');

let options = {
    host : 'AAS0345678008.TEAM-AAS-XXX-INSTALL.ENG.XXXX.NET',
    port: '5683',
    method: 'GET',
    pathname: '/stats',
    query: 'mod=data',
    proxyUri: 'coap://72.121.26.204:5683',
};

let req = coap.request(options);
req.end();
```

Also:
```
$ node --version
v6.10.0
```

If there is an issue with CoAP proxy functionality, it may be unrelated to the error stated in the issue.
The error you received is generated by the OS, unable to resolve a host address.  Try removing the proxyUri option, run the code and see if it generates the error.

**Comment by neophob** [comment]
@jsapna any more inputs from your side? else I will close

**Comment by jsapna** [comment]
you can close it.

**Comment by phretor** [comment]
@jsapna @mcollina a more general question is: can we handle these errors in the calling program?
