### ISSUE TITLE
Multicast discoverable CoAP server

### ISSUE THREAD

**Issue by doapp-ryanp** [mcollina/node-coap#143]
I'm struggling with how to use `node-coap` to create a coap server that is discoverable via multicast per the [CoRE RFC Discovery](https://tools.ietf.org/html/rfc6690#section-1.2.1)

I see [createServer](https://github.com/mcollina/node-coap#createserveroptions-requestlistener) has options for multicast, however if I have multiple coap servers on my network, how do I associate a unique piece of info with each server so clients know which server to connect to?

I know mDNS, and I'd like to get rid if it in favor of CoRE discovery - but I have to admit I'm a noob in this space so not sure how to pull it off.

I'm aware of https://github.com/mcollina/node-coap/issues/53 but it does not help.

**Comment by mcollina** [comment]
Unfortunately I would love to help, but I do not have time to.

**Comment by GiedriusM** [comment]
@doapp-ryanp What you are asking is related to the system design in general and is not node-coap issue. Nevertheless you can use filtering as mentioned in https://tools.ietf.org/html/rfc6690#section-4:

```
Filtering may be performed on any of the link format attributes
using a query string as specified in Section 4.1.  For example,
[GET /.well-known/core?rt=temperature-c] would request resources
with the Resource Type temperature-c.
```

**Comment by doapp-ryanp** [comment]
Thanks guys.

@GiedriusM I'm more struggling with how my server can multicast/broadcast my IP/Hostname so that clients can do a GET  `<discovered IP>/.well-known/core`.

I know how to use mDNS to broadcast ip/host and metadata via txt record, however I can not figure out how to do that using just CoRE.  Is there a npm lib that does core broadcast and discovery?  Or do I need to use mDNS to discover the host, then issue the `/.well-known/core` to said host?

**Comment by GiedriusM** [comment]
What do you mean by client and server? CoAP client and server or application client and server?
What's the problem with service (server?) that wants to be discovered send a broadcast a message, then clients? who received the broadcast message, can send `GET serviceIP/.well-known/core`?

**Comment by daveismith** [comment]
@doapp-ryanp You don't need to know the IP address of the server, you can configure your server with a listener on the CoAP all nodes address (FF0x::FD or 224.0.1.187).

Your devices can then just send a multicast GET to /.well-known/core(?....) to the multicast address you're listening on. Your server then responds (by unicast) with either link format or cbor encoded link format (depending on which RFCs you choose). You can include the explicit IP address of your resource in this response. If you don't, your device must assume it's a relative URI and figure out your IP by examining the address the response came from.

**Comment by koreldan** [comment]
@doapp-ryanp I solved this way:

in the INO sketch i've added`WiFiUDP multicast;`

then at the end of "void setup()" function i've added:`
  IPAddress multi(224, 0, 1, 187); // multicast address to listen to
  uint16_t port = 5683; // multicast port to listen to
  multicast.beginMulticast(WiFi.localIP(), multi, port);  // init to listen to those ip:port`

to test the thing in nodejs code, i've added this code that on start spread a multicast request : `var req = coap.request({
    host: '224.0.1.187',
    method: "GET",
    pathname: '/.well-known/core',
    multicast: true,
    multicastTimeout: 2000
})
.on('response', function(cores) {
                var textChunk = cores.payload.toString('utf8');
                console.log(cores.rsinfo.address);
                console.log(textChunk);
                //res.end(textChunk, 'utf-8');
            })
.end()`

I've an ESP8266 and a WeMOS D1 and both replied with the list of serving functions in it.
