### ISSUE TITLE
Can CoAP preserve data order?

### ISSUE THREAD

**Issue by rynop** [mcollina/node-coap#146]
I am trying to transmit sensor data from an IoT device via CoAP.  The order of the data, as it arrives to the CoAP server is important to me.  I can not find a way to preserve the sequence of data, even when using the `confirmable` request option.

I have a small program below that easily shows what I mean.  Can CoAP not be used if order/sequence of data is important?

```
'use strict';

const coap = require('coap'),
  cbor = require('cbor'),
  server = coap.createServer();

const sequentialData = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
let incomingData = [];
let numResponses = sequentialData.length;

server.on('request', (req, res) => {
  const obj = cbor.decodeFirstSync(req.payload);
  incomingData.push(obj.data);
  res.end();
});

server.listen(() => {
  const reqOpts = {
    hostname: 'localhost',
    method: 'POST',
    pathname: '/sequential',
    options: {
      Accept: 'application/cbor'
    }
  };

  sequentialData.forEach((item) => {
    const req = coap.request(reqOpts);
    req.write(cbor.encode({
      data: item
    }));

    req
      .on('response', (res) => {
        res.pipe(process.stdout);
        res.on('end', () => {
          if (--numResponses === 0) {
            console.log(`got data in this order`, incomingData);
            process.exit();
          }
        })
      });

    req.end();
  });
});
```

**Comment by GiedriusM** [comment]
CoAP is sent via UDP, which does not provide any mechanisms for reliable or sequential transmission. Neither does CoAP as it works on a simple request/response model and is not session/stream based. If you need those properties, then you should use a TCP based messaging protocol or implement a custom packet reordering mechanism in your application.
That being said, in large majority of networks UDP packets USUALLY arrive either in order or are dropped.

**Comment by neophob** [comment]
I'm closing this, as I don't see any pending task here
