### ISSUE TITLE
How can I send multiple CoAP requests?

### ISSUE THREAD

**Issue by bart84** [mcollina/node-coap#151]
I am trying to send few CoAP requests one by one using coap-node. And I only get back the first one which is sent.

var req = coap.request('coap://localhost/.well-known/core'); // <-- only this one gives a response
var req2 = coap.request('coap://192.168.1.2/advanced');
var req3 = coap.request('coap://192.168.1.90/xml');
   
Is it achievable to get responses from all of the three requests? (I understand that they will be asynchronous)

**Comment by GiedriusM** [comment]
You should be able to get responses from multiple requests. Do other requests (req2 and req3) work if you perform them separately? Please make sure that the destination addresses, ports and services are accessible.
