### ISSUE TITLE
Help with observe functionality

### ISSUE THREAD

**Issue by naveenkumarmarri** [mcollina/node-coap#153]
Hi,

This isn't an issue but didn't find any online help on this.
I'm trying to implement observe functionality in my coap server.
So far, I've a coap server which gets data from sensors in cbor format with some payload.
Now I'm trying to implement observe functionality.so that, clients connecting to coap server will get notifications.
Are there any examples on how to achieve this?

**Comment by GiedriusM** [comment]
Hi, @naveenkumarmarri! There are observe client and server example files in the `examples` folder.

**Comment by boneskull** [comment]
@naveenkumarmarri please let me know if this doesn't solve your issue
