### ISSUE TITLE
Is it possible to run it over ZigBee protocole 

### ISSUE THREAD

**Issue by MehdiBenmesa** [mcollina/node-coap#160]

**Comment by GiedriusM** [comment]
Hi @MehdiBenmesa, node-coap runs on top of IP layer, so if your ZigBee devices support IPv4 or IPv6 and can run node.js programs then yes. Otherwise you will need to look for ZigBee specific CoAP implementations.

**Comment by MehdiBenmesa** [comment]
Hi @GiedriusM  thank you for your response. Actually, i am using Xbee radio for communication and Ii want to run CoAP over it, so it is not possible in this case ?!
