### ISSUE TITLE
Problem with multicast Timeout

### ISSUE THREAD

**Issue by straccio** [mcollina/node-coap#161]
Good morning,
i have an issue caused by multicastTimeout.
In my environ, i do a coap multicast get request in order to get info from all devices. The get return successful, but the socket closes after the multicastTimeout causing that can't reuse the agent (i my case the globalAgent) for other requests.

**Comment by GiedriusM** [comment]
Hi @straccio, could you provide an example code?

**Comment by PanzerHabba** [comment]
Hi @GiedriusM 

My issue is related to this. I don`t receive a 'timeout' event on my multicast-request.
coap-version: 0.23.1
Setup:
* 1 rpi with openthread borderRouter connected to nrf52-DK with NCP
* 2 nrf52 DK with openthread/coap stack.

I send a GET multicast-message from rpi to my thread-network.
I then receive a coap-response from both thread-devices, but my 'timeout'-handler never fires.

See code below:
`coap_server.listen({}, () => {
  console.log("COAP Server listening on " + SERVER_HOST + ":" + SERVER_PORT);
  incoming_message_count = 0;

  const options = {
    host: 'ff03::1',
    multicast: true,
    multicastTimeout: 10000,
    confirmable: true,
    port: SERVER_PORT,
    method: "GET",
    pathname: "/question"
  };
  const payload = Buffer.from([0x04]);
  var req = coap.request(options);
  req.write(payload);
console.log('\n\nsending "quizStart" multicast message');

  req.on("response", res => {
    // message received from end-device
    if (res.code == "2.00") {
      incoming_message_count++;
      console.log("response ok from device: ", res.rsinfo.address.slice(-19));
    }
  });

  req.on("timeout", () => {
    console.log("message timed out.");
    console.log(`got response from ${incoming_message_count} devices`);
  });

  req.on("end", () => {
    console.log("request sent");
    process.exit(0);
  });

  req.end();
});`
