### ISSUE TITLE
When running as proxy, neither 'request' event fires nor is createServer's requestListener callback called

### ISSUE THREAD

**Issue by tobyfoo** [mcollina/node-coap#162]
The API documentation states that the server's 'request' event is "Emitted each time there is a request" but I'm not sure if this means to include proxied requests when running with the proxy option set to true.

In examples/proxy.js there is a proxyHandler function [1] which is never fired so I'm assuming the 'request' event really is expected.

If someone could provide the desired behavior I would be happy to submit a PR which either updates the documentation and example or will cause the event to be fired on proxies requests.

[1]: https://github.com/mcollina/node-coap/blob/9335cbcdc6c0d5b6e58abb545461d7393fda66fe/examples/proxy.js#L30

**Comment by GiedriusM** [comment]
For me, it would make more sense if proxied requests did not trigger `request` callback as proxy is not supposed to handle them (i.e. send a separate response). IMO proxyHandler should only be called for direct requests to proxy (see modification below). Other than that I have no objective arguments for this.

```javascript
if (proxied) {
    req.port = 6780;
    //req.proxyUri = 'coap://localhost:8976';
}
```

How did you come across this issue? If you have any arguments why it should be one way or another, I would be happy to hear them.

**Comment by tobyfoo** [comment]
I agree the `request` event (which also calls the `request` callback) should not fire on proxied requests. This is how the library/server behaves currently and I was confused by the proxy.js example.

In the proxy.js example, removing the proxyUri option from the req in sendRequest as you demonstrated would cause the server at port 6780 to behave like a normal server and not a proxy, the proxyHandler callback's name could be misinterpreted in this case. At least that happened to me. As the proxyHandler function is never called in the unmodified example I could provide a PR to remove it. Then no one would expect it to be called on proxied requests.

(@GiedriusM - Thanks for your reply and sorry for the delay with mine.)

**Comment by GiedriusM** [comment]
In such case it could be argued that proxyHandler function shows that a proxied request will NOT call a request handler. Removing it would actually increase the ambiguity. IMO the best solution here is either to leave it as it is, or add a comment(s) that explicitly state how it is supposed to act.
