### ISSUE TITLE
Request with TTL

### ISSUE THREAD

**Issue by ea2973929** [mcollina/node-coap#166]
I'm requesting some data through multicast using .request(). During development it would be nice to restrict the TTL of these packages to just my local network (TTL 0). 

Is there a way to do this with node-coap currently. If not, could it be added?

**Comment by lfk** [comment]
Probably a bit late for your use-case, but answering anyways in case others come looking. :)

```js
const coap = require('coap')

coap.globalAgent._sock.bind({}, () => {
  coap.globalAgent._sock.setMulticastTTL(3)
})
```

Alternatively you can create a new Agent with a custom socket and pass that as a configuration parameter to your request call.
