### ISSUE TITLE
Release v0.22.0

### ISSUE THREAD

**Issue by neophob** [mcollina/node-coap#167]
As the latest v0.21 is not that brand new anymore and some fixes and features were added, i think it make sense to tag a new version and bump the npm release too.

@GiedriusM let me know if you agree, then i'll bump the version and you could deploy to npm.

**Comment by GiedriusM** [comment]
@neophob, I agree 100%!

**Comment by neophob** [comment]
@GiedriusM do you have time for a 0.22.0 release soon? or should I give it a try? Not sure about npm publish

**Comment by GiedriusM** [comment]
Do you want to do it before merging/reviewing current PRs and issues or after? If no new changes are necessary, I will do it.

**Comment by neophob** [comment]
i vote for release now, there are alqays reasons to delay

**Comment by GiedriusM** [comment]
Done

**Comment by neophob** [comment]
great stuff, thanks @GiedriusM !
