### ISSUE TITLE
Repetitive packets with same messageId 

### ISSUE THREAD

**Issue by levshkatov** [mcollina/node-coap#169]
I make 5 simultaneous GET requests to 5 different hosts. The problem is that sometimes I receive same packets with same messageId. Did anybody face this problem?

**Comment by GiedriusM** [comment]
Hi @levshkatov ,

Could you elaborate more on how your setup is working? Maybe you're having packet loss and packets are retransmitted. Did you try capturing traffic on all 6 hosts?

**Comment by jogry** [comment]
in case of wakama code. messageId generated with a "rand()". and seed value set "srand(time(NULL)". as we know "time(NULL)" generate value in second.
if there are many client that connect to server at same time. they all use same seed value to generate messageId. so all of them have same messageId.
you have to use another unique seed value to generate messageId, not only time.
