### ISSUE TITLE
Plugtest Example

### ISSUE THREAD

**Issue by bsmelo** [mcollina/node-coap#170]
Hello,

Does someone have a more complex server-side example using this library, with more resources (and thus exploring possibilities of an observable resource, a block-based resource, etc, all in the same application)? It doesn't need to be a plugtest-server such as [1], but more of a complex one would do, as in [2]. Or can someone point me to where I could find such sample application using this lib?

Thanks & Regards,
Bruno Melo.

[1] https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/PlugtestServer.java
[2] https://github.com/Tanganelli/CoAPthon/blob/master/coapserver.py

**Comment by GiedriusM** [comment]
You can have a look at projects that depend on coap: https://www.npmjs.com/browse/depended/coap

Has resources, observations, but no block transfers: https://github.com/8devices/restserver-api/tree/master/8dev_emulate/nodes

**Comment by bsmelo** [comment]
Now *that* is a nice package manager feature... I'm not used to npm (or node.js, for that matter), and didn't know this one.
Thanks a lot! :)
