### ISSUE TITLE
Put request 

### ISSUE THREAD

**Issue by TAutiomaan** [mcollina/node-coap#171]
I want to make a PUT Request for a remote resource on the url coap: //coap.me/sink and change its value, with node cli i made it using: [echo -n 'new_val' | coap get coap: //coap.me/sink], but in a JavaScript program using node-coap I could not do it.
My question is how to do it in the JavaScript program
thank you in advance

**Comment by GiedriusM** [comment]
Hi @TAutiomaan,

To make a PUT request you have to set request options:
```js
const coap = require('coap');

var requestOptions = {
  host: 'coap.me',
  port: 5683,
  pathname: '/sink',
  method: 'PUT',
};

var req = coap.request(requestOptions);

req.on('response', resp => {
  console.log('Got response:', resp.code, resp.payload.toString());
});

req.end();
```

More info https://github.com/mcollina/node-coap#requesturl

**Comment by JsonMa** [comment]
> Hi @TAutiomaan,
> 
> To make a PUT request you have to set request options:
> 
> ```js
> const coap = require('coap');
> 
> var requestOptions = {
>   host: 'coap.me',
>   port: 5683,
>   pathname: '/sink',
>   method: 'PUT',
> };
> 
> var req = coap.request(requestOptions);
> 
> req.on('response', resp => {
>   console.log('Got response:', resp.code, resp.payload.toString());
> });
> 
> req.end();
> ```
> 
> More info https://github.com/mcollina/node-coap#requesturl

Here is the right answer and i'll close this issue.
