### ISSUE TITLE
CoAP Proxying to HTTP

### ISSUE THREAD

**Issue by ans-4175** [mcollina/node-coap#179]
Hey guys, I have a use case in my company where I need to use existing REST API on HTTP to be used by CoAP protocol. So that I won't rewrite my REST Application on CoAP.
In that case I implemented my proxy app using your lib. Its function will receive request with payload for body and header through CoAP and send it to REST API using HTTP with same url as CoAP requests, and when responses from HTTP got back I just wire it back to CoAP response as `application/json` format for client response.

I wonder if this use case could be a nice feature for this library. So people would use this CoAP library also as their proxy protocol for CoAP <-> HTTP. Because its similarities CoAP and HTTP REST, I think this feature would help many people adapt CoAP as their protocol for constrained device by take advantage from their existing REST API.

How do you guys think? I would like to help.
cc @mcollina

**Comment by mcollina** [comment]
I’m not currently maintaining this.

**Comment by GiedriusM** [comment]
@ans-4175 You should create a separate node module that uses node-coap, but add's on HTTP REST API wrap layer.

**Comment by ans-4175** [comment]
Ooh, okay I already did that @GiedriusM .
Just wondering if it could be added as a feature for this lib (proxying for http).
Thanks for your answer guys, you made a good lib for CoAP.
