### ISSUE TITLE
Unable to specify non-5683 port

### ISSUE THREAD

**Issue by systemmonkey42** [mcollina/node-coap#184]
If I specify a port. either through
'coap://localhost:9000/' or via the '{ host:'localhost', port:9000 }' 
The coap packet never sends.  I'm tracking the network, and due to NAT on the device end (4G network) the device IP changes, as does the port.

When I receive a message from it, I immediately issue a request, however when I convert ths 'rsinfo' details into request host details, the request doesn't send.

Any ideas?

**Comment by systemmonkey42** [comment]
My apologies.  I finally tracked the problem, but it wasn't the destination port.
The SOURCE port is randomly selected.  In this scenario where an outgoing packed opens a temporary hole in the NAT firewall between two hosts, the return packet MUST have the same origin as the outgoing packet.

Imagine, packet from DEVICE (192.168.1.1:5683) -> firewall (publicip:21220) -> server (fixed IP: 5683)

The original response appears to be from "fixed ip: 5683" to (publicip:21220) and is correctly forwarded to DEVICE on the internal network.

However, when subsequently calling 'request', The request originates from 'publicip:randomport' and travels to (publicip:21220) at which point it is discarded as unknown.

My problem must be with the configuration/use of the 'agent'

How can I configure the outgoing 'request' to use the bound port which the server is using? 
Is there a 'server.agent' I can pass to the client to ensure the originating socket is re-used?

Thanks for your help so far.  Sorry for being so far off-base originally.

**Comment by SoftHardDevolop** [comment]
Have you solved this problem? 
I had the same problem. I solved it by setting Agent as 5683 and the SOURCE port has changed port 5683.

**Comment by systemmonkey42** [comment]
I can't see a way to fix this.

The solution will probably involve managing my own port and calling coap-packet directly.

**Comment by systemmonkey42** [comment]
The solution turned out to be fairly straight forward;

Step 1 - create a server;
```
var coapserver = coap.createServer( { port: 5683 } );
```

Step 2 - Create an Agent using the server socket; (not the port, but the actual socket)

```
var myAgent = new coap.Agent( { socket:coapserver._sock} );
```

Step 3 - ensure you include the agent in the request options;

```
var request = coap.request( { method: 'GET', pathname: '/', agent: myAgent });
```

At this point, the request and the server are sharing a socket.  Request responses are received and ignored by the server, while non-response packets are ack'ed by the server and processed correctly.

To be specific, in the product I was interfacing with, the end device initiated a "registration request" (thus I needed to act as a server) then sat back waiting for "observe" requests.  It was important the observe request appeared to originate from the server or they were ignored..

There might be a better way.  My preference would be a server API call which would return a "shared" agent, but for now, reaching into the server structure seem to work.
