### ISSUE TITLE
Error No Reply

### ISSUE THREAD

**Issue by ans-4175** [mcollina/node-coap#185]
Guys, have you encountered this problem?
```
5|echo-ser | Error: No reply in 247s
5|echo-ser |     at Timeout._onTimeout (/home/ubuntu/app/echo-server/node_modules/coap/lib/retry_send.js:70:16)
5|echo-ser |     at ontimeout (timers.js:365:14)
5|echo-ser |     at tryOnTimeout (timers.js:237:5)
5|echo-ser |     at Timer.listOnTimeout (timers.js:207:5)
```
I use my device (client) to send coap payload, often get this error in coap server. But if I use this node-coap client to send message, I didn't receive this error. What is this error about? Is it because my device/client don't send reply after respond from server?

cc @GiedriusM

**Comment by SoftHardDevolop** [comment]
What is your device? Maybe your device has its own communication process. You can try to catch some packet by using WireShark.

**Comment by ans-4175** [comment]
I use `CON`, but if I used `NON-CON` no error whatsoever

**Comment by sjlongland** [comment]
I've seen similar behaviour to the above, using an OpenThread device as the CoAP client, and servers written with `node-coap` directly, and with `coap-polka` (which "wraps" `node-coap`).

What I suspect happens is this:

1. Client sends `CON` message to server with some request.
2. Server `ACK`s it… no payload, schedules the back-end handler to process the request in the NodeJS event loop.
3. Event loop gets around to request handler, which executes, updates the outgoing message (which is itself a `CON` message) and sends it off.
4. Device hears the `CON` reply, acts on it… maybe it sends the `ACK` and it gets lost in transit, or it forgets to `ACK`.
5. Server times out waiting for `ACK` from device, and dies with the above error.

Now, a buggy client should _not_ cause a server crash.  I don't care how wrong it is to not have an `ACK` in reply to a `CON`: if the server's response to this is to just keel over, then that represents an unacceptable denial of service risk as a malicious attacker could send `CON` messages to a server then run away, knowing the server will die 247 seconds later.

It isn't obvious in the API documentation where the `error` event handler should be configured.  No such feature is discussed in the documentation.

**Comment by ans-4175** [comment]
Ah @sjlongland you experienced same problem. How did you manage to handle from server or client side?
In my case, I stayed on NON CON message

**Comment by sjlongland** [comment]
I should point out, using a `NON` message for the request isn't an option in my case because I *want* to know the server received the message sent by the microcontroller.

**Comment by GiedriusM** [comment]
This error is thrown whenever client or server does not receive a response (ACK message) to a confirmable message. I can't answer why it's happening, you will have to debug your network and client to find the reason behind it. You thing you can try to prevent/reduce by changing retry policy with `coap.updateTiming`.

However as I understand the main issue here is not the lost packets, but the coap server crash?
The no reply error is emitted not by the server, but by the response message (request in case of a client).
Below is a snippet of how you can prevent your application from crashing.
```javascript
const coap = require('coap');
const generate  = require('coap-packet').generate;

var coapTiming = {
    ackTimeout: 0.2,
    ackRandomFactor: 1.0,
    maxRetransmit: 1,
    maxLatency: 0.3,
    piggybackReplyMs: 10
};
coap.updateTiming(coapTiming);

const PREVENT_CRASH = true;
const sock = dgram.createSocket('udp4');
const server = coap.createServer((req, res) => {
  console.log('Got request');
  if (PREVENT_CRASH) {
    res.on('error', console.log);
  }
  setTimeout(() => res.end('foobar'), 1000);
});

server.listen(5555, () => {
  let packet = {
    confirmable: true,
  };
  sock.send(generate(packet), 5555);
});
```
Changing PREVENT_CHASH to false, will cause the application to terminate.

**Comment by sjlongland** [comment]
On 18/1/19 12:32 am, Giedrius wrote:
> However as I understand the main issue here is not the lost packets, but
> the coap server crash?

Correct.  A misbehaving CoAP client should _NOT_ cause a server crash, ever.

How well would Github work if all that was needed to bring it down was
to send a web page but not close off the TCP connection with an RST?

> The no reply error is emitted not by the server, but by the response
> message (request in case of a client).
> Below is a snippet of how you can prevent your application from crashing.

Right, so where's this documented so I can learn more?
-- 
Stuart Longland (aka Redhatter, VK4MSL)

I haven't lost my mind...
  ...it's backed up on a tape somewhere.

**Comment by GiedriusM** [comment]
I've created a doc update PR (#199), which describe the events. Feel free to review and/or suggest changes.
