### ISSUE TITLE
url option not working

### ISSUE THREAD

**Issue by symdeb** [mcollina/node-coap#187]
Sending url in a message is not received by the server.

options = [{ host: 'localhost', port: 5683, method:'GET', url:'Matteo' } ]
const req  = coap.request(options)

**Comment by ans-4175** [comment]
You should make your options this way:
```
options = [{ hostname: 'localhost', port: 5683, method:'GET', pathname:'/Matteo' } ]
```
Check this if it works @symdeb

**Comment by lucarv** [comment]
this only works if the hostname is localhost ????
I have a coap server running locally and another in a second machine (machine2)
if i do const req = coap.request('coap://machine2/Matteo), the server in machine 2 gets the request.
if i do options = [{ hostname: 'machine2', port: 5683, method:'GET', pathname:'/Matteo' } ] , the server in machine 2 DOES NOT get the request.

**Comment by ans-4175** [comment]
My bad @lucarv it should be
`options = { hostname: 'localhost', port: 5683, method:'GET', pathname:'/Matteo' }`
An option object, not element of array. I directly pasted and change properties.
Can you confirmed this is worked?

**Comment by lucarv** [comment]
@ans-4175 nope it does not work, it gets worse, see below (i'm partially obfuscating the IP address of the coap device, but you get the idea)

{ hostname: 'coap://XX.XXX.253.157',
  port: 5683,
  method: 'GET',
  pathname: '/Lucarv' }
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND coap://XX.XXX.253.157
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
Emitted 'error' event at:
    at RetrySend.emit (events.js:182:13)
    at /Users/lucarv/source/node/telenet/coap_dev/node_modules/coap/lib/retry_send.js:49:28
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lucarv** [comment]
@ans-4175 Forgot to mention that if i do const req = coap.request('coap://coap://XX.XXX.253.157/Lucarv) the device receives the message, which makes the ENOTFOUND very weird indeed

**Comment by ans-4175** [comment]
Hmm, I cant reproduce it still.
I use IP or DNS still worked in mine.
Care to spare more detail?
