### ISSUE TITLE
Security risk in cache functionality when using a proxy?

### ISSUE THREAD

**Issue by everhardt** [mcollina/node-coap#188]
The LRU and Block2 caches store and retrieve based on `rsinfo.address`, `rsinfo.port`, `packet.messageId` (LRU only) and `packet.token`, see the `toKey` and `toCacheKey` functions in server.js.

If you have a plain UDP proxy in between, the address and port will be the same on all incoming requests for the node-coap server behind the proxy. If a client were to guess the messageId and/or token, wouldn't he then be able to retrieve items from the cache not intended for him? And even without a proxy, aren't clients using the same public IP running the same risk?

There could be other ways to identify a client, for example when using DTLS, the server application might identify the client based on an authentication header (option in CoAP terminology).

A solution might therefore be, to create an extra option `clientIdentifier` in the options object of the `createServer` function. If specified, it should be a function with a signature like `clientIdentifier(request)`, which should return a key that the caches can assume will uniquely identify the client. The implementation can then derive such a key from a request header for example, and by default, it can be
```
clientIdentifier(request) {
  return `${request.rsinfo.address}:${request.rsinfo.port}`;
}
```

**Comment by JKRhb** [comment]
This issue has now been resolved by merging #256.
