### ISSUE TITLE
I can not send the second message on client side, why?

### ISSUE THREAD

**Issue by huge818** [mcollina/node-coap#192]
I can not send the second message on client side

var  coap  = require('../') // or coap

var params={
	host:"127.0.0.1",
	pathname:"/hello",
	query:"",
	observe: true
};

var req  = coap.request(params);

// error
setInterval(function(){
	  req.write("123\n");
},2000);

req.on('response', function(res){);
	 res.on("data",function(data){
		  console.log(111,data.toString());
	 });
});

req.end();

**Comment by huge818** [comment]
can I  execute  req.write after 2 second？

**Comment by ans-4175** [comment]
I think you already end your request right away with `req.end()` thats why
