### ISSUE TITLE
Agent Usage

### ISSUE THREAD

**Issue by qusp66** [mcollina/node-coap#193]
Possibly not an issue, but...
I need to force the CoAP datagram to be always sent on the same UDP PORT. This is a requirement from security to have control on opened ports.
I tried to initialize the globalAgent with a socket option, using the same syntax as expected in dgram
_(globalAgent     = new Agent({ type: 'udp4', socket: {address: '0.0.0.0',port: 61000} })_
That does not work, it fails on a TypeError when trying to call _this_sock.on_

Is there anyway I could achieve my intention?

**Comment by GiedriusM** [comment]
Agent supports `port` parameter. Also you don't need to (and shouldn't) change global agent. Just pass it as agent option when forming a request.

```javascript
const coap = require('coap');
const agent = new coap.Agent({ type: 'udp4', port: 5555});

const req = coap.request({ agent: agent });
req.end();
```
