### ISSUE TITLE
RetrySend does not work properly

### ISSUE THREAD

**Issue by blankm** [mcollina/node-coap#202]
Somehow retrySend is buggy.
When I have an server being offline and send a request to it, the timeout in RetrySend.prototype.send properly fires. 
When I then start my server and rerun the script, all's fine.
Strangely, if I kill the server after the first successful request (or later), the timeout does not fire anymore, the agent simply stops and does nothing. 
Even more confusing, when I debug the scenario with the server being killed after the first successful request (or later), the timeout works again?

But due to the rare comments and the way calls are made when sending (and resending) messages and the different timers, I wasn't able to fully understand the code and identify the part that causes this strange behavior.

**Comment by GiedriusM** [comment]
Hi @blankm, 
Could you clarify how many requests do you send and when the server is stopped? If you could provide some code snippets that recreate the problem that would help too.

**Comment by blankm** [comment]
Basically it's running in an endless loop. The request is always awaited, so the blocking one stops the whole thing. So, what I do to trigger the problem:
I have a coap server running which offers a value. I have a script (see below) that reads that value in a interval (the interval period doesn't have any influence). Once I kill the coap server, the script stops forever at the `await`, no timeout or error is fired. Strangely, if I step through the code, but apart from that, everything the same like written above, an error is emitted. And, as said, if I start the script without the coap server running, also an error is fired immediately. 

It looks like this:

- Init:

```
    this.agent = new coap.Agent();
    
    let coapTiming = {
      ackTimeout:0.25,
      ackRandomFactor: 1.0,
      maxRetransmit: 3,
      maxLatency: 2,
      piggybackReplyMs: 10
    };
    coap.updateTiming(coapTiming);
```

- Inside my loop (only the coap stuff), I call this function readResource and wait to finish with `await`:

``` 
function myLoopWhichIsCalledByATimer(){
   return await readResource("coap://127.0.0.1:5683/dummy");
}
```

```
public readResource(uri): Promise<Content> {
    return new Promise<Content>((resolve, reject) => {

      let requestUri = url.parse(uri);
      let options: CoapRequestConfig = {
        agent: this.agent,
        hostname: requestUri.hostname,
        port: parseInt(requestUri.port, 10),
        pathname: requestUri.pathname,
        query: requestUri.query,
        observe: false,
        multicast: false,
        confirmable: true
      };
      options.method = 'GET';
   
      let req = this.agent.request(options);
      

      req.on("response", (res: any) => {
        console.log(`CoapClient received ${res.code} from ${uri}`);
        console.debug(`CoapClient received Content-Format: ${res.headers["Content-Format"]}`);
        
        // FIXME does not work with blockwise because of node-coap
        let contentType = res.headers["Content-Format"];
        
        resolve({ contentType: contentType, body: res.payload });
      });
      req.on("error", (err: Error) => reject(err));
      req.on("timeout", () => {
        console.log(`CoAP client got timeout when accessing ${uri}`);
        reject("Timeout");
      });
      req.end();
    });
  }
```

**Comment by blankm** [comment]
PS: 

> how many requests do you send

I send one after the other. As soon as the server is killed, the stack stops sending any retries after the first one failed. I don't whether that relates to the ICMP message that comes after the server is killed telling that the port is closed. On the other hand, I found this problem on a, embedded device, that sometimes misses packtes and does not reply because of that, which also stops the script like above, and this device does definitely not send any ICMP messages.

**Comment by GiedriusM** [comment]
I can't reproduce the issue. Here's my code, please check if anything's off:

server.js
```javascript
const coap = require('coap');

let counter = 0;

const server = coap.createServer();
server.listen(5683);

server.on('request', (req, res) => {
  res.end('Count' + counter++);
});
```

client.js
```javascript
const coap = require('coap');
const url = require('url');

class Test {
  constructor() {
    this.agent = new coap.Agent();
  }

  readResource(uri) {
    return new Promise((resolve, reject) => {

      let requestUri = url.parse(uri);
      let options = {
        agent: this.agent,
        hostname: requestUri.hostname,
        port: parseInt(requestUri.port, 10),
        pathname: requestUri.pathname,
        query: requestUri.query,
        observe: false,
        multicast: false,
        confirmable: true
      };
      options.method = 'GET';
   
      let req = this.agent.request(options);
      

      req.on("response", (res) => {
        console.log(`CoapClient received ${res.code} from ${uri}`);
        console.debug(`CoapClient received Content-Format: ${res.headers["Content-Format"]}`);
        
        // FIXME does not work with blockwise because of node-coap
        let contentType = res.headers["Content-Format"];
        
        resolve({ contentType: contentType, body: res.payload });
      });
      req.on("error", (err) => {
        console.log('Request error');
        reject(err);
      });
      req.on("timeout", () => {
        console.log(`CoAP client got timeout when accessing ${uri}`);
        reject("Timeout");
      });
      req.end();
    });
  }

  async process(){
    return await this.readResource("coap://127.0.0.1:5683/dummy");
  }
}

const test = new Test();
  
let coapTiming = {
  ackTimeout:0.25,
  ackRandomFactor: 1.0,
  maxRetransmit: 3,
  maxLatency: 2,
  piggybackReplyMs: 10
};

coap.updateTiming(coapTiming);

async function main() {
  while (1) {
    console.log('Processing...');
    await test.process()
      .catch((err) => { console.log(`Got process error ${err}`); });
  }
}

main();
```

I run start server.js on one process and client.js on another one and get a flood of packets. After killing server process `Got process error Error: No reply in 6s` is printed.

**Comment by blankm** [comment]
> please check if anything's off
As far as I've seen not. I tried again several times, and strangely enough, one time I couldn't reproduce the error as well.

But I tracked it down now, and I at least know, that the reason why no further requests are sent out and everything is reset is because of agent.js ln 116
`this._closing = true`

which leads later again in agent.js ln 402ff that this is called
```
if (that._closing && that._msgInFlight === 0) {
      that._doClose()
```
as result of the first request being sent. Although an answer is not yet there for the request, _doClose is called and consequently in doclose, all is reset
`this._msgIdToReq[k].sender.reset()` which includes the backoff-timer for the request that causes the problem.

**Comment by blankm** [comment]
Finally found the bug:
If you pass a socket to the agent, the following happens:
The last request is done, `cleanUp` is called, `_closing` is set true and `doClose` is set. So far, alright.
But if `_init` is then called for the next request, the socket exists, so
```
if (this._sock) {
    return
  }
```
lets the function return, and so `_closing` which must be set to false when calling `_init` is left at true, because `_closing` ist set to false again just at the very end of `_init`.

**Comment by danielpeintner** [comment]
@GiedriusM is there any update?

**Comment by kevinresol** [comment]
Any update on this?
