### ISSUE TITLE
Multiple responses to a multicast request

### ISSUE THREAD

**Issue by mateusz-** [mcollina/node-coap#205]
Hi,

The README.md states the following:
```markdown
multicast: (...) Several response events will be emitted for each received response.
```

This does not seem to be the case. The callback gets called only once, from what I can see.

Here's a Wireshark summary:
```
1 0.000 fdde:ad00:beef::b2f8:7526:d5a2:6f51   CoAP    NON, MID:32309, GET, TKN:50 53 1c d5, /v1/info
2 0.046 fdde:ad00:beef::b57c:7833:400:0       CoAP    NON, MID:10036, 2.05 Content, TKN:50 53 1c d5, /v1/info
3 0.048 fdde:ad00:beef::15d2:fce4:0:d000      CoAP    NON, MID:16973, 2.05 Content, TKN:50 53 1c d5, /v1/info
4 0.054 fdde:ad00:beef::b2f8:7526:d5a2:6f51   CoAP    RST, MID:16973, Empty Message
```

Frame 1 is a multicast request to `ff03::2`. Frame 2 and 3 are responses. Frame 4 is generated as a response to frame 3 (i.e., it is sent to `fdde:ad00:beef::15d2:fce4:0:d000`) by node-coap. This should not be happening (RST), unless a timeout was reached (it hasn't). The `response` callback gets called once for response from `fdde:ad00:beef::b57c:7833:400:0` (frame 2).

My JavaScript looks like this:
```js
const controllers = {};

const req = coap.request({
  host: 'ff03::2',
  pathname: '/v1/info',
  port: 3002,
  method: 'GET',
  confirmable: false,
  retrySend: 0,
  multicast: true,
  multicastTimeout: 2000,
});

req.on('response', res => {
  try {
    const controller = JSON.parse(res.payload.toString());
    controllers[controller.id] = controller;
  } catch(err) {
    debug.error('CoAP GET /v1/info error', err);
  }
});

req.end();

setTimeout(() => {

  res.data.msg = controllers;

  next();

}, 2001);
```

I created a [fix to this in my own fork](https://github.com/mateusz-/node-coap/commit/53f191e93202da72eabdbe6be646ee2c19070bc9), haven't created a pull request yet though. All tests pass. I did think about creating a new test for this, but this would require multiple servers listening on the same port that handle a multicast request. These servers would have to be mocked up, I believe. Currently, servers are not mocked.

If my fix looks good, I'll create a pull request.

**Comment by GiedriusM** [comment]
Hi @mateusz-,

Thank you for raising the issue.

> The callback gets called only once, from what I can see.

Which version of coap are you using? I've tested the following code with v0.23.1 coap and it seems to work. Could you check it on your system and see if there's any difference?

```javascript
const coap = require('coap');
const dgram = require('dgram');

const sock = dgram.createSocket('udp6');
sock.bind(3002, () => {
  sock.setMulticastLoopback(true);
  sock.addMembership('ff03::2');
});

const server1 = coap.createServer((req, res) => {
  console.log('Request on server 1');
  res.end();
});
server1.listen(sock);

const server2 = coap.createServer((req, res) => {
  console.log('Request on server 2');
  res.end();
});
server2.listen(sock);

const req = coap.request({
  host: 'ff03::2',
  pathname: '/v1/info',
  port: 3002,
  method: 'GET',
  confirmable: false,
  retrySend: 0,
  multicast: true,
  multicastTimeout: 2000,
});

req.on('response', res => {
  console.log('Got response');
});

req.end();
```

> I did think about creating a new test for this, but this would require multiple servers listening on the same port that handle a multicast request.

Unless it is a simple bug (like a typo) or scenario is difficult to automate, there should be a test. That way everyone can reproduce the problem and future changes will not (inadvertently) brake it.

> Currently, servers are not mocked.

In some test cases they are, so there should be no problem with that.

**Comment by mateusz-** [comment]
Thanks for your response, @GiedriusM.

Yes, so that works. I looked into why though - it looks like, in this case, [the request is retrieved using the message id](https://github.com/mcollina/node-coap/blob/8906df697ef64cc5d33c1154f4251143e1cddeb3/lib/agent.js#L137).

It doesn't have to be though, [it can also be retrieved using the token](https://github.com/mcollina/node-coap/blob/8906df697ef64cc5d33c1154f4251143e1cddeb3/lib/agent.js#L150):

>    2.  In a piggybacked response, the Message ID of the Confirmable
       request and the Acknowledgement MUST match, and the tokens of the
       response and original request MUST match.  In a separate
       response, just the tokens of the response and original request
       MUST match.

The above is from IETF CoAP spec, [rfc7252, section 5.3.2](https://tools.ietf.org/html/rfc7252#section-5.3.2). In my case, I am sending a CoAP NON request and responding with a NON (so, not piggybacked).

The following doesn't work in the current master:
```javascript
const coap = require('coap');
const dgram = require('dgram');

const sock = dgram.createSocket('udp6');
sock.bind(3002, () => {
  sock.setMulticastLoopback(true);
  sock.addMembership('ff03::2');
});

const server1 = coap.createServer((req, res) => {
  console.log('Request on server 1');
  res._packet.messageId = res._packet.messageId - 1;
  res.end();
});
server1.listen(sock);

const server2 = coap.createServer((req, res) => {
  console.log('Request on server 2');
  res._packet.messageId = res._packet.messageId + 1;
  res.end();
});
server2.listen(sock);

const req = coap.request({
  host: 'ff03::2',
  pathname: '/v1/info',
  port: 3002,
  method: 'GET',
  confirmable: false,
  retrySend: 0,
  multicast: true,
  multicastTimeout: 2000,
});

req.on('response', res => {
  console.log('Got response');
});

req.end();
```

This is exactly the same as the earlier example, but with different message ids specified in the response. In this case, callback gets called only once. In my fork, callback gets called twice.

I will try to write up a test for this.
