### ISSUE TITLE
 EHOSTDOWN exception

### ISSUE THREAD

**Issue by schmupu** [mcollina/node-coap#209]
I am using the lib for Shelly devices. Once the while I get following exeption: `EHOSTDOWN 192.168.20.115:5683`
Unfortunately I do not have a chance to caught the exception.

**Comment by Apollon77** [comment]
As additional information: It seems to come from sending:

```
const req = coap.request({
                host: ip,
                //port: 5683,
                method: 'GET',
                pathname: '/cit/d'
            });
```
to an IP that went offline in the meantime

**Comment by Apollon77** [comment]
Can be closed, we fixed it by using lib correctly
