### ISSUE TITLE
Timeout in retry_send

### ISSUE THREAD

**Issue by vervaekejonathan** [mcollina/node-coap#210]
Hi!
Running node-coap to send messages to multiple thread nodes.
Sometimes (randomly?) I get the following error:

> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: No reply in 247s
>     at Timeout._onTimeout (/home/pi/thread-otbr-app/application/node_modules/coap/lib/retry_send.js:74:16)
>     at ontimeout (timers.js:482:11)
>     at tryOnTimeout (timers.js:317:5)
>     at Timer.listOnTimeout (timers.js:277:5)

How can I avoid this error? Are there any parameters available so I can change the timeout or even disable this check?
Thanks

**Comment by Apollon77** [comment]
Make sure to subscribe to the "error" and "timeout" events on the coap server

**Comment by JsonMa** [comment]
@vervaekejonathan This event emit when retry send timeout, did you throw the timeout error anywhere?

**Comment by Apollon77** [comment]
I will close here because for me it is a user error ...
