### ISSUE TITLE
Error URI order 

### ISSUE THREAD

**Issue by Saifer707** [mcollina/node-coap#217]
Hi!

I'm using your library for a coap-based client. 
I created 2 db_path with different uri: `/Mobius/test_coap/pontoon_titania/data` and `/Mobius/test_coap/pontoon_titania/camera/blue` (oneM2M compliant). 

When i sent request to `data`, my request is received from server correctly and the URI order is: 
Mobius, test_coap, pontoon_titania, data. 

But when i sent request to `blue`, server get error and the URI order is: 
Mobius, pontoon_titania, camera, blue, test_coap (so url si `/Mobius/pontoon_titania/camera/blue/test_coap` that doesn't exist).

Why am i facing this error?
Thanks!

**Comment by JKRhb** [comment]
@Saifer707 Hi! Have you been able to resolve the issue in the end? Or was it still a problem?

**Comment by Saifer707** [comment]
@JKRhb Hi! Unfortunaly, my job on Mobius was stopped. I didn't try to resolve the issue anyway, I'm sorry. If you have good news, please tell me!
