### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by Apollon77** [mcollina/node-coap#223]
* "devDependencies": {
    * "pre-commit": "1.1.3", ---> why hard pinned? newest is 1.2.2 ... no changelog, no releases, lets hope they do sematic, test it
    * "chai": "^3.4.1", ---> newest 4.2.0, should work
    * "mocha": "^3.2.0", ---> newest 8.0.1, should work
    * "timekeeper": "^1.0.0", --> newest 2.2.0 ... only "freeze" behaviour changed, so should have no effect
    * "sinon": "~1.7.3" ---> newest 9.0.2 ... should work, basically nodejs version changes, test it

*  "dependencies": {
    * "bl": "^1.0.0", ---> newest 4.0.2 ... 2.x added a feature, 3.x removed node 4+5, 4.x added a feature ... should work
    * "capitalize": "^1.0.0", ---> newest 2.0.3 ... is lowercasing rest of string now, used for http headers so should work (https://github.com/mcollina/node-coap/blob/master/lib/helpers.js#L41)
    * "coap-packet": "^0.1.12", ---> 0.1.14, should be easy
    * "debug": "^2.2.0", ---> newest 4.1.1 ... 3.x added features and updated libs, 4.x dropped nodejs 4+5 an change deps. should work too
    * "fastseries": "^1.7.0", ---> newest 2.2.0 ... removed a callback we do not use (releaesed), should work
    * "lru-cache": "^4.0.0", ---> newest 5.1.1 ... haha "remove older node versions" ... no info which ggrrr ... but es6 classes should work node10+, should work
    * "readable-stream": "^2.2.2" ---> newest 3.6.0 ... this is hard to see ... hope tests see it ... need to test @JsonMa  what do you think?

**Comment by Apollon77** [comment]
nearly all deps are outdated and have at least one major version increase ... This means we need to check all libs for breaking stuff and update code if needed. I will start collecting ...

**Comment by Apollon77** [comment]
PS: I hate projects without changelog or proper changelogs in releases ... ;-)

**Comment by Apollon77** [comment]
I started checking it ... mocha is a bitch at the moment .. rest seems to work when trusting the tests

**Comment by JsonMa** [comment]
> PS: I hate projects without changelog or proper changelogs in releases ... ;-)

Me too... So we should add change log to this project.

**Comment by Apollon77** [comment]
> So we should add change log to this project.
ooohh yees :-)
But in fact with node-coap you can scan the releases and you have it ... so it's not that bad here :-)
