### ISSUE TITLE
Switch testing to GitHub Actions

### ISSUE THREAD

**Issue by Apollon77** [mcollina/node-coap#224]

**Comment by JsonMa** [comment]
@Apollon77 Code coverage is also needed. Maybe, i can submit a mr to add it.

**Comment by Apollon77** [comment]
I use github actions in some other projects and also have kind of a "template" for me ... this also integrates with a (at least in my eyes) helpful release tool which is doing releases incl tag and release creation and also manages changelog partly.

I think adding this is very easy ... but the idea of such a release script needs discussion :-) @mcollina 

https://github.com/Apollon77/meross-cloud/blob/master/.github/workflows/test-and-release.yml
uses: https://github.com/AlCalzone/release-script/blob/master/README.md

**Comment by mcollina** [comment]
go for it.

**Comment by mcollina** [comment]
Please __don't move to any CI-based release process__.

**Comment by mcollina** [comment]
Manual releases with 2FA enabled.

**Comment by Apollon77** [comment]
> Manual releases with 2FA enabled.

ok, so we can leave release script out :-)

**Comment by JKRhb** [comment]
@JsonMa Have you been working on this issue yet? Otherwise I would submit a PR for this issue soon :)

**Comment by mcollina** [comment]
go for it!
