### ISSUE TITLE
Introduce Stale bot

### ISSUE THREAD

**Issue by Apollon77** [mcollina/node-coap#229]
@mcollina any thoughts about stale bot? 
I use https://probot.github.io/apps/stale/ in other proejcts with basically this config:

https://github.com/Apollon77/ioBroker.tuya/blob/master/.github/stale.yml

What do you think about using it to get the 48 issues revalidated by the users and only work on relevant stuff

**Comment by mcollina** [comment]
go for it.

**Comment by mcollina** [comment]
> What do you think about using it to get the 48 issues revalidated by the users and only work on relevant stuff

Please make this 2 weeks unless there is a specific "bug" label

**Comment by Apollon77** [comment]
I would be for "2 weeks" unkless "bug" or "enhancement" label?
