### ISSUE TITLE
Update to -observe draft 13

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#23]
http://tools.ietf.org/html/draft-ietf-core-observe-13

**Comment by JKRhb** [comment]
@sjlongland I guess this issue should now be resolved as well? Or do you see any basic observe features that are still missing from the implementation? If I see it correctly [there haven't been](https://datatracker.ietf.org/doc/html/draft-ietf-core-observe-16#appendix-B) any substantial changes after draft 13.

**Comment by sjlongland** [comment]
@JKRhb It does appear that way.  I wrote that code based on the RFC-7641 spec as published which was published September 2015, vs that document which was December 2014.

**Comment by JKRhb** [comment]
@sjlongland Great, then I'll close this issue as well :)
