### ISSUE TITLE
Problem with multicast membership

### ISSUE THREAD

**Issue by BobFrankston** [mcollina/node-coap#231]
Since I'm listening on multiple addresses and adapters and in order to get coap to work I had to put a try/catch around the multicast listener

```
        try {   // RMF 2020.03.23
            that._sock.addMembership(that._multicastAddress, _interface)
        }
        catch (e) {
            console.error(`${e.message} Adding ${that._multicastAddress}`);
        }
```
I now get 
```
addMembership EINVAL Adding 224.0.1.187
addMembership EINVAL Adding 224.0.1.187
addMembership EINVAL Adding 224.0.1.187
```

which is better than failing. I don't if this is the best we can or if there is a better solution. For now, I'm modifying my various after install until there is a better approach.

**Comment by Apollon77** [comment]
How your code looks like? What you give as "adderess for the coap.listen ?

EINVAL normally says that there is something wrong with the value you provided, so the try catch is only a failsafe that do not really adress the root cause

**Comment by Apollon77** [comment]
And you are also sure that the addMembership adress you provided is the correct one?

**Comment by Apollon77** [comment]
ALso: Which OS you are using? Linux? WIndows? which nodejs version?

**Comment by BobFrankston** [comment]
Sorry about not responding sooner -- for some reason I'm not getting notifications. This is on Windows and I'm using the package indirectly via https://www.npmjs.com/package/shellies. I added more information

```
addMembership EINVAL Adding 224.0.1.187 binding(5683 interface(192.55.226.39))
addMembership EINVAL Adding 224.0.1.187 binding(5683 interface(192.168.0.39))
addMembership EINVAL Adding 224.0.1.187 binding(5683 interface(169.254.0.39)
```
These are multiple addresses on the same interface. Since this is via the event interface I'll need to do more work to figure out the origin. Or is this enough info?

**Comment by JsonMa** [comment]
`
'use strict'

const dgram = require('dgram');
const socket = dgram.createSocket('udp4')
socket.bind(8081, () => {
    socket.addMembership('224.0.0.100')
    socket.setMulticastLoopback(true) // enable loopback
    socket.send('multicast message', 8081, '224.0.0.100')
})
socket.on('message', (msg, rinfo) => {
    console.log(`received form ${rinfo.address}:${rinfo.port} ${msg}`); // received the multicast message
});`
@BobFrankston Here is my multicast example, and  I hope it can help you.

**Comment by BobFrankston** [comment]
The problem is that there are multiple addresses for the Ethernet interface and the CoAP puts up an addMembership for each address rather than each interface.

**Comment by JsonMa** [comment]
> The problem is that there are multiple addresses for the Ethernet interface and the CoAP puts up an addMembership for each address rather than each interface.

Maybe it's not about CoAP, it's about UDP.
