### ISSUE TITLE
Release version 0.25.0

### ISSUE THREAD

**Issue by JKRhb** [mcollina/node-coap#258]
I created this issue to remind ourselves to release a new minor version of `node-coap` and publish it to `npm` :)

**Comment by Apollon77** [comment]
ooohhh ... know what ... felt off my radar completely ... sorry ... I will do tomrrow!

**Comment by Apollon77** [comment]
We have anything on master and use this right?

**Comment by JKRhb** [comment]
> ooohhh ... know what ... felt off my radar completely ... sorry ... I will do tomrrow!

Awesome! :) No worries, I haven't been thinking about it myself for a couple of weeks 😅

> We have anything on master and use this right?

Yeah, I think master should be ready to be released :)

**Comment by Apollon77** [comment]
Will be delayed till tomorrow ...  need to collect all stuff for changelog first ... big one

**Comment by Apollon77** [comment]
@JKRhb https://github.com/mcollina/node-coap/pull/259 please check ... then we can go I think

**Comment by Apollon77** [comment]
npm relelase done

**Comment by JKRhb** [comment]
> npm relelase done

Yay! Thank you very much! :)
