### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by JKRhb** [mcollina/node-coap#305]
Over the last few months there have been a number of changes that have been introduced to the project. Most of them have been refactoring or clean up but there are also a couple of new features (new methods and content-formats as well as preliminary Typescript support).

As the merge of #293 will probably only be able in about a week I was wondering if we should maybe already publish a new (minor) release or wait until #293 has been merged. I was also wondering if the Typescript release could be version 1.0.0 or if there are still important features missing that should be implemented first. As there haven't been any breaking API changes the TS release it could also be declared as another minor one.

What do you think, @Apollon77 and @invaderb?

**Comment by invaderb** [comment]
@JKRhb Did you mean to reference 293 for both versions or is there another pr you are talking about?

I don't really see any reason why we can't go to a version 1.0.0, I guess it depends on how strict we'd like to follow semver
From the spec 
https://semver.org/#spec-item-4
_Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable._

Are we considering that node-coap is truly in a stable state? I use it in production at my company and suggest it to customers using it as a template for training for coap and how it works.

**Comment by invaderb** [comment]
AH ok that sounds good to me!

I'll comment about the DTLS stuff in your other ticket you opened.

**Comment by Apollon77** [comment]
Hey,

sorry for my absence, needed to spent a week to work after Amazon changes and this desttoyed some of my other plans. I finish one project and then I check all PRs and get back here.

Sorry for me blocking here :-(

Ingo

**Comment by Apollon77** [comment]
Ok, so I merge #307, then we publish 0.26.0 ... Then we merge #293 and do an 1.0.0 afterwards?! Right?

**Comment by JKRhb** [comment]
> Ok, so I merge #307, then we publish 0.26.0 ... Then we merge #293 and do an 1.0.0 afterwards?! Right?

Yeah, sounds good :)

**Comment by Apollon77** [comment]
0.26.0 released ...

**Comment by Apollon77** [comment]
TS PR also merged, I opened one to update deps ... when we do 1.0? ;-))

**Comment by Apollon77** [comment]
should we also do 1.0 "now" or wait some days?

**Comment by JKRhb** [comment]
> should we also do 1.0 "now" or wait some days?

Sorry for the late response! I think we could already go for a 1.0.0 release now... Or do you see anything that should be added first?

**Comment by Apollon77** [comment]
Ok, so to summarize ... we now remove changelog.md and move over to releases docs only right? Then we should do one last dependency check and pot update deps and then release 1.0 ... do you want then to create the release tag ... and I then release it?

**Comment by JKRhb** [comment]
> do you want then to create the release tag ... and I then release it?

Sure, sounds good :) I opened #321 for the preparation of the new release. To ensure the `1.0.0` tag doesn't get lost on `master` (which is one of the scenarios I thought about when I opened #318) maybe we can merge that PR with a merge commit?

**Comment by Apollon77** [comment]
Done

**Comment by JKRhb** [comment]
> Done

Awesome :) I already created a release here on Github, could you publish the new version to npm?

**Comment by JKRhb** [comment]
> npm release done,

🎉

> btw for future : DO we also want to publish typescript files? ;-))

As there also source map files provided I think my intent by including them was to allow users of the library to jump to the original typescript source code. Not sure if that actually works already but if it does I think it is a bit nicer than jumping to a declaration file when trying to inspect the implementation of a function or class.

**Comment by Apollon77** [comment]
Then we can close here or?

**Comment by JKRhb** [comment]
> Then we can close here or?

Yeah, I think so :)

**Comment by Apollon77** [comment]
1.0.1 done

**Comment by JKRhb** [comment]
> 1.0.1 done

Awesome, thank you!
