### ISSUE TITLE
Change merge method for PRs to "Create a merge commit"?

### ISSUE THREAD

**Issue by JKRhb** [mcollina/node-coap#318]
So far commits are always squashed when a PR is merged. To make the tracking of changes easier we might consider creating a merge commit instead. In this case, however, we might add the requirement of performing a rebase before a PR is merged to ensure a clean commit history.

What do you think? @Apollon77 @invaderb

**Comment by Apollon77** [comment]
Agreed. Yes it is not "hard defined" but in my experince working best.

**Comment by Apollon77** [comment]
But I think @mcollina needs to adjust that in the repo settings :-) ... if he also agreeed to this "convention"

**Comment by invaderb** [comment]
Honestly I've never been a fan of rebasing, but I don't a strong opinion to not do it just a personal thing.

**Comment by mcollina** [comment]
I prefer the squash than the rebasing.

**Comment by JKRhb** [comment]
Thank you for your input everyone :) I think we can conclude that we keep the current procedure.
