### ISSUE TITLE
Client observe does not work for large message

### ISSUE THREAD

**Issue by desireesantos** [mcollina/node-coap#325]
On the client side, I want to observe a resource with a large message and I'm getting a bad request as a status code.
I would like to intensify that for small and medium messages(size until 1K), it works well.

` ...
  const setup = {
    host: 'CLOUD_IP',
    observe: true,
    port: 5683,
    pathname: '/middlewareToCloud',
    method: 'GET'
}   
 const req = coap.request(setup)`

I had added the option Block2, but it did not work:
`
    req.setOption('Block2', Buffer.of(0x2))`

What do I need to do to get the payload for the large message? 
Am I doing something wrong or is it an issue for a large message?

**Comment by desireesantos** [comment]
I don't know if it can help, but it's the current response.

`ObserveReadStream {
  _readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    paused: true,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null
  },
  readable: true,
  _events: [Object: null prototype] {
    close: [Function],
    deregister: [Function]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  payload: <Buffer >,
  options: [],
  code: '4.00',
  method: undefined,
  headers: {},
  url: '/',
  rsinfo: { address: 'CLOUD_IP', family: 'IPv4', port: 5683, size: 12 },
  outSocket: { address: '0.0.0.0', family: 'IPv4', port: 56920 },
  _packet: {
    code: '4.00',
    confirmable: false,
    reset: false,
    ack: true,
    messageId: 60029,
    token: <Buffer 89 fb ce 8a d6 ce 64 a8>,
    options: [],
    payload: <Buffer >
  },
  _payloadIndex: 0,
  _lastId: undefined,
  _lastTime: 0,
  _disableFiltering: false,
  [Symbol(kCapture)]: false`

**Comment by JKRhb** [comment]
Hi! Thanks for reporting the issue :) Could you try out a bigger block size? You can increase argument in the buffer up to `0x06` (for the maximum blocksize of 1024 bytes), maybe this could help?

**Comment by desireesantos** [comment]
I changed the block2 to`req.setOption('Block2', Buffer.of(0x6))`

<img width="646" alt="Screenshot 2021-12-03 at 10 40 17" src="https://user-images.githubusercontent.com/986738/144612208-9b416364-4e5e-4050-8d3f-bd4ea194efb1.png">

**Comment by JKRhb** [comment]
Hmm, that is strange :/ I found no indication in the specification both for blockwise and observe that could hint why this is interpreted as a bad request. Does sending the observe request without the block2 option set also lead to an error?

Perhaps it could also be an issue with the server implementation? Is the server also using node-coap or using another library?

**Comment by desireesantos** [comment]
Good point @JKRhb!
From server-side is another library[(libcoap)](https://libcoap.net/). 
**I'll will change from libcoap to node-coap to check!**

Currently, I use the Copper plugin to execute some tests and I can get large messages using this plugin.
<img width="1676" alt="Screenshot 2021-12-03 at 11 30 14" src="https://user-images.githubusercontent.com/986738/144619498-15f03390-bee7-49d6-952b-61dbdde5e420.png">
