### ISSUE TITLE
dotenv conflict with latest version

### ISSUE THREAD

**Issue by invaderb** [mcollina/node-coap#328]
Hey guys,

 I noticed on a new project I'm setting up that dotenv is having an issue with the latest version on node-coap, with dotenv preloaded requests no longer come in.
"dev": "node -r dotenv/config ./src/server.js",
dotenv was working with version 0.25.0

Im also on node version 14 but going to try latest of that as well in a bit.

No errors are showing up so I'm not sure where to start looking

**Comment by Apollon77** [comment]
Hm ... I would not know where node-coap relies on env variables at all ... so honestly: Does it work without dotenv?

Else enable debug log and show whats happening ....

**Comment by invaderb** [comment]
Yeah I enabled debug log to see if I could see anything and nada

**Comment by invaderb** [comment]
![Screen Shot 2022-03-02 at 2 01 47 PM](https://user-images.githubusercontent.com/16693116/156449124-bb5ac964-7862-4832-8880-806928b6a716.png)

**Comment by invaderb** [comment]
starts working just fine but local env vars don't get loaded :(
![Screen Shot 2022-03-02 at 2 04 44 PM](https://user-images.githubusercontent.com/16693116/156449504-4cf99b51-427e-4ccd-b99c-dc5c6c8a7e3f.png)

**Comment by invaderb** [comment]
Not sure if this is an issue with dotenv blocking the incoming requests but wouldn't make much sense as it's just loading the env var into the process with node first starts up

**Comment by Apollon77** [comment]
@JKRhb any idea? I can not imagine that it should make any difference

**Comment by JKRhb** [comment]
Hmm :/ Maybe this is somehow caused by the switch to typescript?

**Comment by invaderb** [comment]
I think this might actually be an issue with the node project using ESModules, I finally got an error with dotenv running just a simple http server
![Screen Shot 2022-03-02 at 2 20 08 PM](https://user-images.githubusercontent.com/16693116/156451518-cea502fd-9f76-4299-acc0-b0b7e9e8d353.png)
r

**Comment by invaderb** [comment]
well nvm I realized I has a spelling error >.< it did work with the node http module so back to square one

**Comment by invaderb** [comment]
@JKRhb are you able to reproduce for a sanity check?

**Comment by invaderb** [comment]
🤦  I have no idea why but I started removing my env vars one by and and I removed my server PORT var and it started working

**Comment by invaderb** [comment]
so something like this is not working
```
const port = process.env.S_PORT || 65011;
server.listen(port, () => {
	console.log(Date());
	console.log('\n=================================================\nCOAP LISTENER running at port ' +
	`${port}` + `\n Worker ${process.pid} is listening ` +
	'\n=================================================\n');
});
```

**Comment by invaderb** [comment]
ah ok figured it out, due to the migration to TS a check must has been added to ensure the port is a number.

This works
```javascript
const port = parseInt(process.env.S_PORT) || 65011;
server.listen(port, () => {
	console.log(Date());
	console.log('\n=================================================\nCOAP LISTENER running at port ' +
	`${port}` + `\n Worker ${process.pid} is listening ` +
	'\n=================================================\n');
});
```

**Comment by JKRhb** [comment]
> @JKRhb are you able to reproduce for a sanity check?

Oh, sorry for the late response! :/

> ah ok figured it out, due to the migration to TS a check must has been added to ensure the port is a number.

Oh, awesome that you could figure it out 🎉 Would you consider this issue resolved then? Or do you think some kind of documentation should be added in case others run into the same problem?

**Comment by invaderb** [comment]
@JKRhb yeah I just think a quick little note next to the port in the readme would suffice! :) especially since pre 1.0.0 it could take in a string

**Comment by JKRhb** [comment]
> @JKRhb yeah I just think a quick little note next to the port in the readme would suffice! :)

That sounds good :)

> especially since pre 1.0.0 it could take in a string

I think the documentation in general could probably be updated – either in the README or maybe auto-generated using the TS typings and Github Actions, for example. The structure of the possible parameters for each method/constructor is pretty complex IMHO and not that well reflected at the moment.

...but I guess that is step we can take after documenting the new port parameter ;)
