### ISSUE TITLE
GET with observable=true and confirmable=false with Philips-Air devices do not work since 0.26

### ISSUE THREAD

**Issue by Apollon77** [mcollina/node-coap#332]
It seems that soething between 0.25 and 0.26 broke GET with observable=true and confirmable=false with Philips-Air devices,

Most likely broken by commit https://github.com/mcollina/node-coap/commit/f35b58a57acb9b86645a5691712e6a1c5f567fd4

Details see https://github.com/iobroker-community-adapters/ioBroker.philips-air/issues/15

Effect is that simply no data is emitted

**Comment by JKRhb** [comment]
As the original issue was resolved by #345, I think we can also close this one :)
