### ISSUE TITLE
Blockwise 'block1' mode

### ISSUE THREAD

**Issue by sdeceuninck** [mcollina/node-coap#42]
Hi,

it seems that the 'block1' mode is not implemented. There is only 'block2' mode.
Part 2.3, in the IETF document, it's written that block1 mode should be use in case of a POST or a PUT to the server and block2 in a response (GET).

Looking at the agent.js file, there is nothing concerning block1.

Thanks
Sylvain

**Comment by mcollina** [comment]
Hi Sylvain, I am really low on bandwidth at the moment, would you like to help on that? Let's make this library a community effort!

**Comment by sdeceuninck** [comment]
I'll do my best but i'm not a developper. So I will try to help as much as i can.

**Comment by SimCordy** [comment]
Hi, with the library is possible to transfer data in blockwise mode to the server via post or put method?
