### ISSUE TITLE
`url` in req means `path` instead of the real `url`

### ISSUE THREAD

**Issue by stackOverMind** [mcollina/node-coap#47]
When I make a request  `coap://localhost/aa/bb` to the server ,`req.url` equals `/aa/bb` ,should it be `coap://localhost/aa/bb` ?

**Comment by mcollina** [comment]
It follows the http module in core:
http://nodejs.org/api/http.html#http_message_url
Il giorno gio 5 mar 2015 alle 07:38 stackOverMind <notifications@github.com>
ha scritto:

**Comment by neophob** [comment]
timedout
