### ISSUE TITLE
Test "request should emit the errors in the req" fails with timeout

### ISSUE THREAD

**Issue by spemmons** [mcollina/node-coap#48]
I note that Travis-CI shows the build passing, so maybe I've got some kind of incompatibility. I'm running using node version 0.10.36 on the Mac and 0.10.29 on a Debian BeagleBone image 2015-03-01. The same problem occurs on both using "npm test" to execute the tests. Here is the exact error...

```
1) request should emit the errors in the req:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/root/node-coap/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

Any suggestions? Thanks!

**Comment by mcollina** [comment]
They all pass fine here with node v0.10.36 on the Mac.

**Comment by dmoranj** [comment]
This kind of errors may happen occasionally depending on the server load or other external conditions. Did you manage to repeat it? If it was a transient error, I think we can just let it pass (probably it was just a transient condition that trigger it). If you can repeat it deterministically, maybe something in your environment is blocking UDP packets, or maybe the Node version is not high enough. Please try with the version Mateo mentioned and repeat the tests.

**Comment by neophob** [comment]
tests were updated, i close this almost 3 years old ticket
