### ISSUE TITLE
POST method in server.js

### ISSUE THREAD

**Issue by latapata** [mcollina/node-coap#49]
Hello All,

I am entirely new to Node.js in COAP. I need to accomplish a simple task using server.js. I will send some data using POST from a client and the server should be able to store it in a variable. 

Can somebody please suggest me what modifications i should make in server.js

**Comment by mcollina** [comment]
You should use [concat-stream](http://npm.im/concat-stream).

```
req.pipe(concat(function(yourdata) {
  console.log(yourdata)
}))
```

**Comment by latapata** [comment]
Hello @mcollina I did it by using global variable. Your suggestion also helped me thanks for the answer
