### ISSUE TITLE
How to read Token and Message Type?

### ISSUE THREAD

**Issue by ClaesNilsson** [mcollina/node-coap#50]
Hi,

I am experimenting with this excellent library and have two questions:

* How to read the Token field in a GET Observe response? Could it also be set in the request?

* How to read the Message Type (Confirmable, Non-Confirmable, Acknowledgement, Reset) in a response?

**Comment by mcollina** [comment]
All of it is in a `_packet`  property of the request/response. It is supposed to be private.
Feel free to send a pr to improve/update anything ;)

**Comment by ClaesNilsson** [comment]
Thanks for reply but I am not sure that I follow. What do you mean by "private" in this context?
 If I send a request `var req = coap.request(myReq);` and receives the response with 
` req.on('response', function(res) { 
            
          // Handle received Obeserve messages on the ObserveReadStream  
          res.on('data', function(msg) {......................`

how do I get the Token and Message fields from the `_packet` property?

**Comment by mcollina** [comment]
By "private" I mean it is not part of the formal API of this module, so I can break that anytime.

Basically `req._packet.token`.

**Comment by ClaesNilsson** [comment]
For the response I tried `res._packet.token` but got the error message that _packet was undefined. What I was trying to achieve was that when an application has sent an Observe GET request to a CoAP server, the first response from the server should be an ACK and the next and following responses should be Confirmable Observe messages. I was interested in seeing that and that the token was the same to confirm the flow.

Of course it is possible to just assume that the first response from the CoAP server to an Observe GET request is an ACK and the remaining responses are Confirmable Observe messages. Which is your view on what is needed here?

**Comment by mcollina** [comment]
Observe is already supported here, so there is no need to do that. just call res.write() multiple times to send multiple messages on a Observe request.

**Comment by ClaesNilsson** [comment]
Thanks for your replies Matteo,

Yes, the Observe sequence could be managed without setting and reading the Token field. I also wonder how to use a "separate response" to a GET request with your library. For example, see slide 25 in http://www.slideshare.net/zdshelby/coap-tutorial?next_slideshow=1. If the server wants to reply with a later separate response and `response` is the `OutgoingMessage` object should then the first empty ACK be coded as:

`response.code = "0.00"; `
`response.write();`

and when the data is ready to be sent
`response.code = "2.05"; `
`response.end("my new data");`

Correct?

**Comment by mcollina** [comment]
No. all that is handled automatically by the library with a 50ms timeout, see https://github.com/mcollina/node-coap/blob/master/lib/outgoing_message.js#L32-L46.

**Comment by ClaesNilsson** [comment]
Ok, thanks
