### ISSUE TITLE
IPV6 client requests

### ISSUE THREAD

**Issue by latapata** [mcollina/node-coap#51]
Hey I have to make IPV6 requests to my COAP server located at some IPV6 address. say 2001:131:aabc:12::1 for example. 

How do I put that information in the client example of coap node js

Thanks in advance for the reply.

**Comment by mcollina** [comment]
you can pass an IPv6 everywhere you can pass an IPv4.
Il giorno ven 10 apr 2015 alle 16:54 latapata <notifications@github.com> ha
scritto:

**Comment by latapata** [comment]
Thanks for the information.
