### ISSUE TITLE
Improve time-related tests to make them safer

### ISSUE THREAD

**Issue by dmoranj** [mcollina/node-coap#52]
There are some tests, labeled "should retry four times before 45s" that fail from time to time, by retrying 5 times instead of 4. That's a typical problem with time-related tests and we should try to make them safer (we are already using the timers, so we should be able to fine-tune this somehow).

**Comment by mcollina** [comment]
Please do, those tests are so buggy.

**Comment by neophob** [comment]
duplicate

**Comment by neophob** [comment]
can be closed, fixed with issue #104
