### ISSUE TITLE
Resource discovery of a COAP Server using node js coap client

### ISSUE THREAD

**Issue by latapata** [mcollina/node-coap#53]
Hello All,

I have a standard coap server implemented. by using a node js coap client I want to discover the available resources in the coap server. How can I do it using the node js coap client ?

Thank you in advance for the reply.

**Comment by mcollina** [comment]
I have no example for this, but it would be great if you write a module to handle that! Have a look at the spec for `/.well-know/core` and the Link format.

**Comment by mcollina** [comment]
Than send a PR to the README, so we can refer to your module!

**Comment by latapata** [comment]
@mcollina yes lately I found that .well-known/core gives me. The pain is parsing the string. I am doing it i will let you know when it is done. I do not know how to write node js modules so I will take some time to do that.

**Comment by hmahida** [comment]
@latapata any update on " .well-known/core" implementation as module ?

**Comment by mcollina** [comment]
Not really, but if you want to give it a stab, I would be very happy to add a link here and an example.

**Comment by hmahida** [comment]
@mcollina ok, thanks, I am looking at .net implantation of " .well-known/core". Let see, I will update here if anything promising ..!!! any way fantastic work by you @mcollina . thanks for node-coap.
