### ISSUE TITLE
Handler not called when proxyUri not present

### ISSUE THREAD

**Issue by dmoranj** [mcollina/node-coap#55]
Identified by @ClaesNilsson

If a server received a request without a proxyUri field the handler of the server should be called instead of forwarding to another target server. This does now work, no handler is called in this case.

**Comment by dmoranj** [comment]
@ClaesNilsson, checking this bug, it seems the scenario is covered by the 'with a non-proxied request should call the handler as usual' test in the `proxy.js` test file, so the basic case seems to be working. Can you provide a simple example to reproduce the bug? Thanks.

**Comment by ClaesNilsson** [comment]
Ok, I will provide a test case. However, I am just about to go on a business trip so may not be able to provide the test case until Friday this week.

**Comment by dmoranj** [comment]
Found the problem with your examples, thank you. The problem was the createServer() method did not pass along the "listener" method, so it was not subscribed to the 'request' event. I'll propose a PR ASAP.
