### ISSUE TITLE
Proxy blocks observe responses

### ISSUE THREAD

**Issue by dmoranj** [mcollina/node-coap#56]
Identified by @ClaesNilsson

If a GET observe request is sent through the proxy then only the first response of the request is received.

**Comment by dmoranj** [comment]
I've tried to reproduce with tests (view PR #57) and it won't reproduce. Can you provide a simple example to reproduce it? Can you give us more information about the version of your environment or any other factors that may be affecting the test? Thanks.

**Comment by ClaesNilsson** [comment]
Ok, I will provide a test case. However, I am just about to go on a business trip so may not be able to provide the test case until Friday this week.

**Comment by dmoranj** [comment]
Ok, when you want. Once we have the test case we will start working on solving it.

**Comment by dmoranj** [comment]
Also find the problem: the proxy removes the request entry once it has been answered, but that's wrong in the case of the Observer requests. I'll change that to add an exception.
