### ISSUE TITLE
'index out of range' error

### ISSUE THREAD

**Issue by neich** [mcollina/node-coap#58]
Hi,

I'm getting this error while performing some GETs on real devices:

```
buffer.js:506
    throw new RangeError('index out of range');
          ^
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt32BE (buffer.js:580:5)
    at Agent.handle [as _handle] (/..../coap-ngsi-agent/node_modules/coap/lib/agent.js:222:39)
    at Socket.<anonymous> (/..../coap-ngsi-agent/node_modules/coap/lib/agent.js:65:10)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

Since it is very difficult to produce a simple test case, I'm attaching the debuggin session just at the point where it fails. It seems that at some point, `lib/agent.js` is trying to call `readUInt32BE` on an empty buffer.

Any hints?

![coap_problem](https://cloud.githubusercontent.com/assets/1770949/7703737/42b85b4e-fe3a-11e4-8042-7ec21a8d7122.png)

**Comment by dmoranj** [comment]
Can you provide some Wireshark traces of what's happening at the network
level? We can try to reproduce the test case based on that.

**Comment by neich** [comment]
This is the first time I use wireshark, so be patient ...

What I'm doing is:

- Now I'm using Cooja with 2 devices and an edge router
- First I send an HTTP GET to the router so I get the list of neighbors
- Then for each neighbor I send a discovery
- For each discovery I send a GET for each link

I'm using Ipv6 and the addresses of the two devices are ```aaaa::212:7402:2:202``` and ```aaaa::212:7403:3:303```

The smallest capture that I've been able to produce is this: https://www.dropbox.com/s/jnitgy9fh1r9cdh/coap_problem.pcapng?dl=0

Thanks !!

**Comment by neich** [comment]
Ok, I've narrowed it down to this COAP message:

```
0000   60 a3 14 3c ff 41 6c 72 65 61 64 79 49 6e 55 73  `..<.AlreadyInUs
0010   65                                               e
```

It seems that coap-packet parses the msg ok, but then it tries to delete a token that does not exists.

**Comment by neich** [comment]
I've solved this changing the last else to:

```
else if (!req.url.observe && packet.token.lenght > 0)
```

Is this correct?

**Comment by neich** [comment]
Should I create a PR for this?

**Comment by mcollina** [comment]
yes please! :)
Il giorno dom 19 lug 2015 alle 19:27 neich <notifications@github.com> ha
scritto:
