### ISSUE TITLE
Multicast Support

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#6]
At the moment, __node-coap__ does not support multicast communication, as it it does not expose any API to add/remove the membership to a group.

**Comment by edhemphill** [comment]
@mcollina Partial server-side support is here... I'll try to do a pull request as soon as I have more time. 
https://github.com/WigWagCo/node-iotivity/tree/master/lib/node-coap

**Comment by mcollina** [comment]
@edhemphill I suggest you to depend on the library via NPM, and not to maintain your custom fork :). If you need to depend to your own version for some time, you can use a git dependency in package.json.

Anyway, this is an OPEN Open Source Project, so if it is ok with you I will add you to the maintainers list as soon as this is merged :).

**Comment by edhemphill** [comment]
Go for it -- sorry for the delay. Yes, we would prefer to use it from NPM. Thanks!

**Comment by mcollina** [comment]
Added you to this repo, feel free to contribute to a feature branch/pull request here :).

**Comment by edhemphill** [comment]
Will do soon - thanks

**Comment by pastukhov** [comment]
Any progress?

**Comment by mcollina** [comment]
As said before, if anybody wants to contribute i will be more than happy!

**Comment by neophob** [comment]
should be fixed, right?

**Comment by mcollina** [comment]
Yes it is.
