### ISSUE TITLE
Move to standard code style?

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#62]
What do you think of adopting [standard](npm.im/standard)?

**Comment by dmoranj** [comment]
In my projects I usually use JSHint, as I feel more comfortable with that
coding style, but I understand standard may suit node-coap's repository
style better. I think, either way, it's a good idea to have a sintactic
chek for the project's code.

**Comment by mcollina** [comment]
Yes, that's my goal.

I would like to keep this without semicolons, a part from that I am ok.

I like standard because it's a "no config" kind of thing.
