### ISSUE TITLE
Proxy blocks ACKs to Confirmable Observe messages

### ISSUE THREAD

**Issue by ClaesNilsson** [mcollina/node-coap#63]
@dmoranj , thanks for fixing https://github.com/mcollina/node-coap/issues/56. Now GET Observe messages pass the Proxy fine. However, unfortunately there still is a problem as it seems as the ACKs to each Observe message send from the observe client do not pass the proxy.

I got the following error message for the observe server, i.e. the peer that received the GET Observe request and sends CON Observe:
    `Error: No reply in 247s
        at null._onTimeout (C:\node_modules\coap\lib\retry_send.js:61:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15) .`

Checking with Wireshark confirmed that the ACKs were not received by the observe server. When I run without a proxy the ACKs were received correctly.

BR

**Comment by ClaesNilsson** [comment]
@dmoranj, did you have a chance look at this issue?

**Comment by dongyupu** [comment]
as this issue
Proxy blocks ACKs to Confirmable Observe messages

middlewares.js
->handleProxyResponse->request.server._sendReverseProxied(request.packet, originalProxiedRequest.rsinfo)->this._sock.send(message, 0, message.length, port, host, callback)

the agent proxy will lost the real 'request.rsinfo' , agent doesn't save 'proxyUri' .

agent.js

_handle() ->
    if (packet.confirmable) {
        buf = generate({
            code: '0.00',
            ack: true,
            messageId: packet.messageId
        })

        this._msgInFlight++;
        this._sock.send(buf, 0, buf.length, rsinfo.port, rsinfo.address, ackSent);
    }


should i save 'proxyUri'  somewhere in agent

any suggestion for this ?

@mcollina
