### ISSUE TITLE
Possible memory leak when request gets error

### ISSUE THREAD

**Issue by neich** [mcollina/node-coap#64]
Hi,

I'm working in a project that at some point starts to make a COAP GET request every second. If the response is OK there is no problem, heap keeps stable. But if, for example, the network gos down and I start to get ENETUNREACH errors, the heap starts to grow since I got a out of memory error.

I've created a small test to show what I mean:

https://gist.github.com/neich/97743a806fc76ff06932

My understanding is that since there is a 247s timeout for requests, if you start to get ENETUNREACH, all requests are kept until the timeout is fired. But once have passed 247s, requests should be able to be GC and the heap should stop to grow.

In my test, after 1000 sec approx, I got an out of memory error. Does the timeout not clean the request ? Am I missing something ?

Is there a way to abort a request a let it ready for GC ?

Thanks

**Comment by mcollina** [comment]
It is probably leaking. Not sure exactly why, why don't you check this and send a PR?

**Comment by neich** [comment]
Done: #65 

Basically I have added an extra 'timeout' event when the setTimeout callback at RestrySend is called. This allows the Agent to capture the event and do come cleanup, avoiding keeping a reference to a request that never will be completed.

Beware that I have written this fix with no detailed knowledge of the library, so it is likely I've missing something ...

**Comment by neophob** [comment]
merged, can be closed i guess
