### ISSUE TITLE
Crash when receiving two confirmable responses with same message ID & token

### ISSUE THREAD

**Issue by neich** [mcollina/node-coap#69]
Hi,

I'm getting a crash with a long running process that happens very rarely. I've been able to write a test that shows the crash:

https://gist.github.com/neich/b4788c093a100ade7cfe

It seems that if by accident you receive two CON responses with the same message ID & token, it crashes with the second because the library believes is an observable request: there is a req.response from the previous response, but it an OutgoingMessage, an not an ObservableStrem, so .append() fails.

Right now I've solved with this:

```
  if (req.response) {
    if (req.response.append) {
      // it is an observe request
      // and we are already streaming
      return req.response.append(packet)
    } else {
      // TODO There is a previous response but is not an ObserveStream !
      req.response = null
    }
```

but I'm not sure if it's right. Should I PR?

**Comment by mcollina** [comment]
Yes please :)
