### ISSUE TITLE
ignore charset info when converting content format to binary

### ISSUE THREAD

**Issue by boneskull** [mcollina/node-coap#73]
a content format `Content-Type: application/json; charset=utf8` will blow up.  I believe we can strip the semicolon (inclusive) to the end during conversion.

>    CoAP does not include a separate way to convey content-encoding
>    information with a request or response, and for that reason the
>    content-encoding is also specified for each identifier (if any).  If
>    multiple content-encodings will be used with a media type, then a
>    separate Content-Format identifier for each is to be registered.
>    Similarly, other parameters related to an Internet media type, such
>    as level, can be defined for a CoAP Content-Format entry.

**Comment by boneskull** [comment]
alright, I'm not sure what to do with this.  we should allow the options to pass through verbatim.  however, if we strip the charset info from the format in order to match it against, say, `application/json`, then there's a mismatch with buffer length.  I don't understand why the pre-registered formats have the byte values they do.

**Comment by mcollina** [comment]
The formats are part of the coap spec, they are represented as a binary.

Here are the definitions in this library: https://github.com/mcollina/node-coap/blob/66a84eabeb0ed04b7b7d6acec8ea0252a153fb6e/lib/option_converter.js#L73-L78

**Comment by mcollina** [comment]
I don't get the mismatch for the buffer length.

**Comment by boneskull** [comment]
I'll come up with a reproducible case
