### ISSUE TITLE
http header compatibility strategy

### ISSUE THREAD

**Issue by boneskull** [mcollina/node-coap#78]
So I'm wondering to what degree does this module want to allow common HTTP headers?  The spec only defines a few options of course, but for compatibility with modules based on `http`, it'd be cool if we could at least *not throw exceptions* if they want to use headers such as `Cache-Control` or `Content-Length`.

In addition to `registerOption()`, perhaps we can implement an `ignoreOption()`, which just silently tosses out headers which are not applicable?

**Comment by mcollina** [comment]
I think it might be easier to also have a 'strict' mode and a lax mode regarding options. In strict mode, every unknown option throws. In lax mode, they are ignored. What do you think?
