### ISSUE TITLE
Support all options/codes/formats

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#8]
Unofficial with all drafts: http://svn.tools.ietf.org/svn/wg/core/registry.txt

Official: http://www.iana.org/assignments/core-parameters/core-parameters.txt

**Comment by mkovatsc** [comment]
The implementation should revert to number Content-Formats, when no media type string is registered. There is no reason to fail creating the `IncomingMessage` object. Generic clients built with the coap package cannot register all numbers with "unknown", just to allow for reception.
