### ISSUE TITLE
How do you send PUT message with payload?

### ISSUE THREAD

**Issue by pizuricv** [mcollina/node-coap#85]
Hello,
Not sure I get it, is this the way to send PUT message?

  var req = coap.request({host: 'coap://localhost/Matteo', method : 'PUT'})  
  var payload = {
    title: 'this is a test payload',
    body: 'containing nothing useful'
  }
  
  req.write(new Buffer(JSON.stringify(payload)));
  req.on('response', function(res) {
    res.pipe(process.stdout)
  })
  req.end()

**Comment by pizuricv** [comment]
I tested and works, would be great just to have an example on the main page...

**Comment by mcollina** [comment]
Would you mind sending a PR adding this example? Thanks!
