### ISSUE TITLE
Error: No reply in 247s

### ISSUE THREAD

**Issue by neophob** [mcollina/node-coap#88]
I think there is an unhandled error in the retry_send code:

```
Error: No reply in 247s
    at null._onTimeout (/opt/app/node_modules/coap/lib/retry_send.js:69:18)
    at Timer.listOnTimeout (timers.js:92:15)
```

Or do I need to capture this error on app side?

**Comment by mcollina** [comment]
This is an application error. You should listen to the `'error'` event in the request, it should be emitted there.

**Comment by JKRhb** [comment]
> can I change the timeout?

You can, using the `updateTiming` function (see [here](https://github.com/coapjs/node-coap#updateTiming)). For example, you could increase the maximum number of retransmits from 4 to 5:

```ts
const coapTiming = {
    maxRetransmit: 5,
}

updateTiming(coapTiming)
```

Details regarding the individual parameters can be found in [RFC 7252, section 4.8](https://www.rfc-editor.org/rfc/rfc7252#section-4.8).
