### ISSUE TITLE
Node 4 and 5 suppor

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#90]
I see several tests failing on Node v4+. Anybody that would like to help?

**Comment by neophob** [comment]
I bumped most of the deps in package.json - however this still does not resolve those flacky tests. I suspect that the UDP sockets or the emitters fails sometimes.

**Comment by neophob** [comment]
Resolved, bump mocha. I'll send a PR soon

**Comment by mcollina** [comment]
Done.
