### ISSUE TITLE
No Piggybacked answer - no token in request

### ISSUE THREAD

**Issue by neophob** [mcollina/node-coap#93]
I use node-coap as proxy server (or http gateway). If the client request a resource, my server needs to fetch data from a local REST server and returns the result. this means the answer is send delayed. I found interopt tests etsi (http://www.etsi.org/plugtests/CoAP/Document/CoAP_TestDescriptions_v015.pdf) and I assume this is related to this test case:

15 TD_COAP_CORE_15 Interoperate in lossy context (CON mode, delayed response) 

the answer the coap server needs to send is between 140 and 250 bytes. if I send the answer (using a block2 size of 3, max 256 bytes) the client has troubles getting the answer as sometimes it get the answer, sometimes the client retry the request without success. it looks like sometimes the server send empty acks followed by the effective payload (using a different message id).

What's the best option I have to send this payload to the client? using a ETag?

**Comment by mcollina** [comment]
It's really hard to debug this without a reproducing case. Would you like to send a PR that fixes the problem?

**Comment by neophob** [comment]
I'm investigate in this case - I think the main problem is sync messages vs. async messages (non piggybacked answers). I'll create an example code and send a PR.

**Comment by neophob** [comment]
@mcollina I want to verify that a token is included in the request (because of the async messages) - if not I want to send "Token Option required by server (CoAP 240)" error.
Currently the token is included in the internal package structure. I don't want to reference this data structure, so I'll add a new function to verify if a token is set.

**Comment by neophob** [comment]
Ok I invested more time, I think it clear what's wrong. The CoAP Server needs to send a non piggybacked answer - the client however does not include a token - thus the client cannot assign the message to its request because another message id is used.

In a earlier draft (https://tools.ietf.org/html/draft-ietf-core-coap-03) this section is written:

```
If a request does not include a Token option, the server MUST
      provide its ReST response within the transaction response.  If it
      cannot do so (i.e., can only satisfy the request through an
      asynchronous response), it MUST respond with error "Token Option
      required by server (CoAP 240)".
```

however I cannot find a similar section in the final RFC anymore. So I assume this is not true anymore, especially because this note in the final RFC

```
(Note that every message carries a token, even if it is of zero length.)
```

-> long story short - I think node-coap behaves as it should.
