### ISSUE TITLE
Lead maintainer needed

### ISSUE THREAD

**Issue by mcollina** [mcollina/node-coap#97]
As you probably have seen, I have been neglecting this module for the last few months. I think it will be better if someone else does the releases, and ensures general quality of the received contributions.

cc @nqd @dmoranj @neich @boneskull

**Comment by boneskull** [comment]
Unfortunately as I'm not presently using this module, I can't make time to maintain it.

**Comment by mcollina** [comment]
cc @richardms would you like to help?

**Comment by ans-4175** [comment]
Guys, who is maintainers for this packages? I am barely new using your lib as my coap proxy app. Would like to ask and help if I can.

Thanks
