### ISSUE TITLE
Observe cancelled by server

### ISSUE THREAD

**Issue by berchierm** [mcollina/node-coap#98]
The situation is the following:
- A client built with this lib
- A server running on a low energy device with its own lib

When the client send an observe request to the server, at first it works fine. (Server send an ACK and start sending updates)

Then, after 3-4 NON messages from the server, the server send a CON, to check whether there are still clients interested at receiving updates. (according to draft-11 of observe specification, chapter 3.5)

The problem is occurring when the server send a CON message. The client don't acknowledge it, so the server stop sending updates.

As you can see in this wireshark capture, the observe request is sent, the server acknowledge it and start sending updates. Then suddenly the server send a CON, retry to send a CON, and having no response from the client, assume he don't want to receive more update.

<img width="932" alt="coap_observe_not_ack" src="https://cloud.githubusercontent.com/assets/16225774/11688668/44e94410-9e8e-11e5-9eb3-520fb4edea6b.png">

I've used the code from the example "observe_client.js"

``` coap
var coap        = require('coap')
  , req         = coap.request({hostname:'fe80::abcd', pathname: '/lights/led3', observe: true})

req.on('response', function(res) {
  res.pipe(process.stdout)
})

req.end()
```

I've tried about anything I can think of with no result. Am I doing something wrong or is it some kind of bug of the lib? 

Thanks for your help and thanks for this great lib !

**Comment by mcollina** [comment]
Sorry for taking so long to answer: I'd guess that it's a bug in the lib. Would you (or anybody else) send a PR?
